// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMachineReservationServiceServer creates a new instance of MachineReservationServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMachineReservationServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MachineReservationServiceServer {
	mock := &MachineReservationServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MachineReservationServiceServer is an autogenerated mock type for the MachineReservationServiceServer type
type MachineReservationServiceServer struct {
	mock.Mock
}

type MachineReservationServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MachineReservationServiceServer) EXPECT() *MachineReservationServiceServer_Expecter {
	return &MachineReservationServiceServer_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type MachineReservationServiceServer
func (_mock *MachineReservationServiceServer) Added(context1 context.Context, machineReservationReport *v1.MachineReservationReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, machineReservationReport)

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, machineReservationReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationReport) *v1.Empty); ok {
		r0 = returnFunc(context1, machineReservationReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineReservationReport) error); ok {
		r1 = returnFunc(context1, machineReservationReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineReservationServiceServer_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type MachineReservationServiceServer_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - context1 context.Context
//   - machineReservationReport *v1.MachineReservationReport
func (_e *MachineReservationServiceServer_Expecter) Added(context1 any, machineReservationReport any) *MachineReservationServiceServer_Added_Call {
	return &MachineReservationServiceServer_Added_Call{Call: _e.mock.On("Added", context1, machineReservationReport)}
}

func (_c *MachineReservationServiceServer_Added_Call) Run(run func(context1 context.Context, machineReservationReport *v1.MachineReservationReport)) *MachineReservationServiceServer_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineReservationReport
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineReservationReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineReservationServiceServer_Added_Call) Return(empty *v1.Empty, err error) *MachineReservationServiceServer_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MachineReservationServiceServer_Added_Call) RunAndReturn(run func(context1 context.Context, machineReservationReport *v1.MachineReservationReport) (*v1.Empty, error)) *MachineReservationServiceServer_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type MachineReservationServiceServer
func (_mock *MachineReservationServiceServer) Deleted(context1 context.Context, machineReservationReport *v1.MachineReservationReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, machineReservationReport)

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, machineReservationReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationReport) *v1.Empty); ok {
		r0 = returnFunc(context1, machineReservationReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineReservationReport) error); ok {
		r1 = returnFunc(context1, machineReservationReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineReservationServiceServer_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type MachineReservationServiceServer_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - context1 context.Context
//   - machineReservationReport *v1.MachineReservationReport
func (_e *MachineReservationServiceServer_Expecter) Deleted(context1 any, machineReservationReport any) *MachineReservationServiceServer_Deleted_Call {
	return &MachineReservationServiceServer_Deleted_Call{Call: _e.mock.On("Deleted", context1, machineReservationReport)}
}

func (_c *MachineReservationServiceServer_Deleted_Call) Run(run func(context1 context.Context, machineReservationReport *v1.MachineReservationReport)) *MachineReservationServiceServer_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineReservationReport
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineReservationReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineReservationServiceServer_Deleted_Call) Return(empty *v1.Empty, err error) *MachineReservationServiceServer_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MachineReservationServiceServer_Deleted_Call) RunAndReturn(run func(context1 context.Context, machineReservationReport *v1.MachineReservationReport) (*v1.Empty, error)) *MachineReservationServiceServer_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type MachineReservationServiceServer
func (_mock *MachineReservationServiceServer) Modified(context1 context.Context, machineReservationReport *v1.MachineReservationReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, machineReservationReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, machineReservationReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationReport) *v1.Empty); ok {
		r0 = returnFunc(context1, machineReservationReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineReservationReport) error); ok {
		r1 = returnFunc(context1, machineReservationReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineReservationServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type MachineReservationServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - machineReservationReport *v1.MachineReservationReport
func (_e *MachineReservationServiceServer_Expecter) Modified(context1 any, machineReservationReport any) *MachineReservationServiceServer_Modified_Call {
	return &MachineReservationServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, machineReservationReport)}
}

func (_c *MachineReservationServiceServer_Modified_Call) Run(run func(context1 context.Context, machineReservationReport *v1.MachineReservationReport)) *MachineReservationServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineReservationReport
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineReservationReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineReservationServiceServer_Modified_Call) Return(empty *v1.Empty, err error) *MachineReservationServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MachineReservationServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, machineReservationReport *v1.MachineReservationReport) (*v1.Empty, error)) *MachineReservationServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MachineReservationServiceServer
func (_mock *MachineReservationServiceServer) Usage(context1 context.Context, machineReservationUsageRequest *v1.MachineReservationUsageRequest) (*v1.MachineReservationUsageResponse, error) {
	ret := _mock.Called(context1, machineReservationUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.MachineReservationUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationUsageRequest) (*v1.MachineReservationUsageResponse, error)); ok {
		return returnFunc(context1, machineReservationUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReservationUsageRequest) *v1.MachineReservationUsageResponse); ok {
		r0 = returnFunc(context1, machineReservationUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.MachineReservationUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineReservationUsageRequest) error); ok {
		r1 = returnFunc(context1, machineReservationUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineReservationServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MachineReservationServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - machineReservationUsageRequest *v1.MachineReservationUsageRequest
func (_e *MachineReservationServiceServer_Expecter) Usage(context1 any, machineReservationUsageRequest any) *MachineReservationServiceServer_Usage_Call {
	return &MachineReservationServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, machineReservationUsageRequest)}
}

func (_c *MachineReservationServiceServer_Usage_Call) Run(run func(context1 context.Context, machineReservationUsageRequest *v1.MachineReservationUsageRequest)) *MachineReservationServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineReservationUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineReservationUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineReservationServiceServer_Usage_Call) Return(machineReservationUsageResponse *v1.MachineReservationUsageResponse, err error) *MachineReservationServiceServer_Usage_Call {
	_c.Call.Return(machineReservationUsageResponse, err)
	return _c
}

func (_c *MachineReservationServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, machineReservationUsageRequest *v1.MachineReservationUsageRequest) (*v1.MachineReservationUsageResponse, error)) *MachineReservationServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
