// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewNetworkTrafficServiceServer creates a new instance of NetworkTrafficServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetworkTrafficServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetworkTrafficServiceServer {
	mock := &NetworkTrafficServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NetworkTrafficServiceServer is an autogenerated mock type for the NetworkTrafficServiceServer type
type NetworkTrafficServiceServer struct {
	mock.Mock
}

type NetworkTrafficServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *NetworkTrafficServiceServer) EXPECT() *NetworkTrafficServiceServer_Expecter {
	return &NetworkTrafficServiceServer_Expecter{mock: &_m.Mock}
}

// Modified provides a mock function for the type NetworkTrafficServiceServer
func (_mock *NetworkTrafficServiceServer) Modified(context1 context.Context, networkTrafficReport *v1.NetworkTrafficReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, networkTrafficReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkTrafficReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, networkTrafficReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkTrafficReport) *v1.Empty); ok {
		r0 = returnFunc(context1, networkTrafficReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.NetworkTrafficReport) error); ok {
		r1 = returnFunc(context1, networkTrafficReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkTrafficServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type NetworkTrafficServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - networkTrafficReport *v1.NetworkTrafficReport
func (_e *NetworkTrafficServiceServer_Expecter) Modified(context1 any, networkTrafficReport any) *NetworkTrafficServiceServer_Modified_Call {
	return &NetworkTrafficServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, networkTrafficReport)}
}

func (_c *NetworkTrafficServiceServer_Modified_Call) Run(run func(context1 context.Context, networkTrafficReport *v1.NetworkTrafficReport)) *NetworkTrafficServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.NetworkTrafficReport
		if args[1] != nil {
			arg1 = args[1].(*v1.NetworkTrafficReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NetworkTrafficServiceServer_Modified_Call) Return(empty *v1.Empty, err error) *NetworkTrafficServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *NetworkTrafficServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, networkTrafficReport *v1.NetworkTrafficReport) (*v1.Empty, error)) *NetworkTrafficServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type NetworkTrafficServiceServer
func (_mock *NetworkTrafficServiceServer) Usage(context1 context.Context, networkUsageRequest *v1.NetworkUsageRequest) (*v1.NetworkUsageResponse, error) {
	ret := _mock.Called(context1, networkUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.NetworkUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkUsageRequest) (*v1.NetworkUsageResponse, error)); ok {
		return returnFunc(context1, networkUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkUsageRequest) *v1.NetworkUsageResponse); ok {
		r0 = returnFunc(context1, networkUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.NetworkUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.NetworkUsageRequest) error); ok {
		r1 = returnFunc(context1, networkUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkTrafficServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type NetworkTrafficServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - networkUsageRequest *v1.NetworkUsageRequest
func (_e *NetworkTrafficServiceServer_Expecter) Usage(context1 any, networkUsageRequest any) *NetworkTrafficServiceServer_Usage_Call {
	return &NetworkTrafficServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, networkUsageRequest)}
}

func (_c *NetworkTrafficServiceServer_Usage_Call) Run(run func(context1 context.Context, networkUsageRequest *v1.NetworkUsageRequest)) *NetworkTrafficServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.NetworkUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.NetworkUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NetworkTrafficServiceServer_Usage_Call) Return(networkUsageResponse *v1.NetworkUsageResponse, err error) *NetworkTrafficServiceServer_Usage_Call {
	_c.Call.Return(networkUsageResponse, err)
	return _c
}

func (_c *NetworkTrafficServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, networkUsageRequest *v1.NetworkUsageRequest) (*v1.NetworkUsageResponse, error)) *NetworkTrafficServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
