// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewVolumeServiceClient creates a new instance of VolumeServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVolumeServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *VolumeServiceClient {
	mock := &VolumeServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VolumeServiceClient is an autogenerated mock type for the VolumeServiceClient type
type VolumeServiceClient struct {
	mock.Mock
}

type VolumeServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *VolumeServiceClient) EXPECT() *VolumeServiceClient_Expecter {
	return &VolumeServiceClient_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type VolumeServiceClient
func (_mock *VolumeServiceClient) Added(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceClient_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type VolumeServiceClient_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.VolumeReport
//   - opts ...grpc.CallOption
func (_e *VolumeServiceClient_Expecter) Added(ctx any, in any, opts ...any) *VolumeServiceClient_Added_Call {
	return &VolumeServiceClient_Added_Call{Call: _e.mock.On("Added",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *VolumeServiceClient_Added_Call) Run(run func(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption)) *VolumeServiceClient_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeReport
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *VolumeServiceClient_Added_Call) Return(empty *v1.Empty, err error) *VolumeServiceClient_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *VolumeServiceClient_Added_Call) RunAndReturn(run func(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption) (*v1.Empty, error)) *VolumeServiceClient_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type VolumeServiceClient
func (_mock *VolumeServiceClient) Deleted(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceClient_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type VolumeServiceClient_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.VolumeReport
//   - opts ...grpc.CallOption
func (_e *VolumeServiceClient_Expecter) Deleted(ctx any, in any, opts ...any) *VolumeServiceClient_Deleted_Call {
	return &VolumeServiceClient_Deleted_Call{Call: _e.mock.On("Deleted",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *VolumeServiceClient_Deleted_Call) Run(run func(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption)) *VolumeServiceClient_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeReport
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *VolumeServiceClient_Deleted_Call) Return(empty *v1.Empty, err error) *VolumeServiceClient_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *VolumeServiceClient_Deleted_Call) RunAndReturn(run func(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption) (*v1.Empty, error)) *VolumeServiceClient_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type VolumeServiceClient
func (_mock *VolumeServiceClient) Modified(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceClient_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type VolumeServiceClient_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.VolumeReport
//   - opts ...grpc.CallOption
func (_e *VolumeServiceClient_Expecter) Modified(ctx any, in any, opts ...any) *VolumeServiceClient_Modified_Call {
	return &VolumeServiceClient_Modified_Call{Call: _e.mock.On("Modified",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *VolumeServiceClient_Modified_Call) Run(run func(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption)) *VolumeServiceClient_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeReport
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *VolumeServiceClient_Modified_Call) Return(empty *v1.Empty, err error) *VolumeServiceClient_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *VolumeServiceClient_Modified_Call) RunAndReturn(run func(ctx context.Context, in *v1.VolumeReport, opts ...grpc.CallOption) (*v1.Empty, error)) *VolumeServiceClient_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type VolumeServiceClient
func (_mock *VolumeServiceClient) Usage(ctx context.Context, in *v1.VolumeUsageRequest, opts ...grpc.CallOption) (*v1.VolumeUsageResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.VolumeUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeUsageRequest, ...grpc.CallOption) (*v1.VolumeUsageResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeUsageRequest, ...grpc.CallOption) *v1.VolumeUsageResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.VolumeUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeUsageRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceClient_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type VolumeServiceClient_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.VolumeUsageRequest
//   - opts ...grpc.CallOption
func (_e *VolumeServiceClient_Expecter) Usage(ctx any, in any, opts ...any) *VolumeServiceClient_Usage_Call {
	return &VolumeServiceClient_Usage_Call{Call: _e.mock.On("Usage",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *VolumeServiceClient_Usage_Call) Run(run func(ctx context.Context, in *v1.VolumeUsageRequest, opts ...grpc.CallOption)) *VolumeServiceClient_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeUsageRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *VolumeServiceClient_Usage_Call) Return(volumeUsageResponse *v1.VolumeUsageResponse, err error) *VolumeServiceClient_Usage_Call {
	_c.Call.Return(volumeUsageResponse, err)
	return _c
}

func (_c *VolumeServiceClient_Usage_Call) RunAndReturn(run func(ctx context.Context, in *v1.VolumeUsageRequest, opts ...grpc.CallOption) (*v1.VolumeUsageResponse, error)) *VolumeServiceClient_Usage_Call {
	_c.Call.Return(run)
	return _c
}
