// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewClusterServiceServer creates a new instance of ClusterServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterServiceServer {
	mock := &ClusterServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClusterServiceServer is an autogenerated mock type for the ClusterServiceServer type
type ClusterServiceServer struct {
	mock.Mock
}

type ClusterServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterServiceServer) EXPECT() *ClusterServiceServer_Expecter {
	return &ClusterServiceServer_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type ClusterServiceServer
func (_mock *ClusterServiceServer) Added(context1 context.Context, clusterReport *v1.ClusterReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, clusterReport)

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, clusterReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterReport) *v1.Empty); ok {
		r0 = returnFunc(context1, clusterReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ClusterReport) error); ok {
		r1 = returnFunc(context1, clusterReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterServiceServer_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type ClusterServiceServer_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterReport *v1.ClusterReport
func (_e *ClusterServiceServer_Expecter) Added(context1 any, clusterReport any) *ClusterServiceServer_Added_Call {
	return &ClusterServiceServer_Added_Call{Call: _e.mock.On("Added", context1, clusterReport)}
}

func (_c *ClusterServiceServer_Added_Call) Run(run func(context1 context.Context, clusterReport *v1.ClusterReport)) *ClusterServiceServer_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ClusterReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ClusterReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterServiceServer_Added_Call) Return(empty *v1.Empty, err error) *ClusterServiceServer_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ClusterServiceServer_Added_Call) RunAndReturn(run func(context1 context.Context, clusterReport *v1.ClusterReport) (*v1.Empty, error)) *ClusterServiceServer_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type ClusterServiceServer
func (_mock *ClusterServiceServer) Deleted(context1 context.Context, clusterReport *v1.ClusterReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, clusterReport)

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, clusterReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterReport) *v1.Empty); ok {
		r0 = returnFunc(context1, clusterReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ClusterReport) error); ok {
		r1 = returnFunc(context1, clusterReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterServiceServer_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type ClusterServiceServer_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterReport *v1.ClusterReport
func (_e *ClusterServiceServer_Expecter) Deleted(context1 any, clusterReport any) *ClusterServiceServer_Deleted_Call {
	return &ClusterServiceServer_Deleted_Call{Call: _e.mock.On("Deleted", context1, clusterReport)}
}

func (_c *ClusterServiceServer_Deleted_Call) Run(run func(context1 context.Context, clusterReport *v1.ClusterReport)) *ClusterServiceServer_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ClusterReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ClusterReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterServiceServer_Deleted_Call) Return(empty *v1.Empty, err error) *ClusterServiceServer_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ClusterServiceServer_Deleted_Call) RunAndReturn(run func(context1 context.Context, clusterReport *v1.ClusterReport) (*v1.Empty, error)) *ClusterServiceServer_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type ClusterServiceServer
func (_mock *ClusterServiceServer) Modified(context1 context.Context, clusterReport *v1.ClusterReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, clusterReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, clusterReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterReport) *v1.Empty); ok {
		r0 = returnFunc(context1, clusterReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ClusterReport) error); ok {
		r1 = returnFunc(context1, clusterReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type ClusterServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterReport *v1.ClusterReport
func (_e *ClusterServiceServer_Expecter) Modified(context1 any, clusterReport any) *ClusterServiceServer_Modified_Call {
	return &ClusterServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, clusterReport)}
}

func (_c *ClusterServiceServer_Modified_Call) Run(run func(context1 context.Context, clusterReport *v1.ClusterReport)) *ClusterServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ClusterReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ClusterReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterServiceServer_Modified_Call) Return(empty *v1.Empty, err error) *ClusterServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ClusterServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, clusterReport *v1.ClusterReport) (*v1.Empty, error)) *ClusterServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type ClusterServiceServer
func (_mock *ClusterServiceServer) Usage(context1 context.Context, clusterUsageRequest *v1.ClusterUsageRequest) (*v1.ClusterUsageResponse, error) {
	ret := _mock.Called(context1, clusterUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.ClusterUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterUsageRequest) (*v1.ClusterUsageResponse, error)); ok {
		return returnFunc(context1, clusterUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ClusterUsageRequest) *v1.ClusterUsageResponse); ok {
		r0 = returnFunc(context1, clusterUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ClusterUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ClusterUsageRequest) error); ok {
		r1 = returnFunc(context1, clusterUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type ClusterServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterUsageRequest *v1.ClusterUsageRequest
func (_e *ClusterServiceServer_Expecter) Usage(context1 any, clusterUsageRequest any) *ClusterServiceServer_Usage_Call {
	return &ClusterServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, clusterUsageRequest)}
}

func (_c *ClusterServiceServer_Usage_Call) Run(run func(context1 context.Context, clusterUsageRequest *v1.ClusterUsageRequest)) *ClusterServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ClusterUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ClusterUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterServiceServer_Usage_Call) Return(clusterUsageResponse *v1.ClusterUsageResponse, err error) *ClusterServiceServer_Usage_Call {
	_c.Call.Return(clusterUsageResponse, err)
	return _c
}

func (_c *ClusterServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, clusterUsageRequest *v1.ClusterUsageRequest) (*v1.ClusterUsageResponse, error)) *ClusterServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
