// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewIPServiceClient creates a new instance of IPServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPServiceClient {
	mock := &IPServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IPServiceClient is an autogenerated mock type for the IPServiceClient type
type IPServiceClient struct {
	mock.Mock
}

type IPServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IPServiceClient) EXPECT() *IPServiceClient_Expecter {
	return &IPServiceClient_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Added(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type IPServiceClient_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.IPReport
//   - opts ...grpc.CallOption
func (_e *IPServiceClient_Expecter) Added(ctx any, in any, opts ...any) *IPServiceClient_Added_Call {
	return &IPServiceClient_Added_Call{Call: _e.mock.On("Added",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *IPServiceClient_Added_Call) Run(run func(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption)) *IPServiceClient_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPReport
		if args[1] != nil {
			arg1 = args[1].(*v1.IPReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IPServiceClient_Added_Call) Return(empty *v1.Empty, err error) *IPServiceClient_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *IPServiceClient_Added_Call) RunAndReturn(run func(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption) (*v1.Empty, error)) *IPServiceClient_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Deleted(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type IPServiceClient_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.IPReport
//   - opts ...grpc.CallOption
func (_e *IPServiceClient_Expecter) Deleted(ctx any, in any, opts ...any) *IPServiceClient_Deleted_Call {
	return &IPServiceClient_Deleted_Call{Call: _e.mock.On("Deleted",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *IPServiceClient_Deleted_Call) Run(run func(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption)) *IPServiceClient_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPReport
		if args[1] != nil {
			arg1 = args[1].(*v1.IPReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IPServiceClient_Deleted_Call) Return(empty *v1.Empty, err error) *IPServiceClient_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *IPServiceClient_Deleted_Call) RunAndReturn(run func(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption) (*v1.Empty, error)) *IPServiceClient_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Modified(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type IPServiceClient_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.IPReport
//   - opts ...grpc.CallOption
func (_e *IPServiceClient_Expecter) Modified(ctx any, in any, opts ...any) *IPServiceClient_Modified_Call {
	return &IPServiceClient_Modified_Call{Call: _e.mock.On("Modified",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *IPServiceClient_Modified_Call) Run(run func(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption)) *IPServiceClient_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPReport
		if args[1] != nil {
			arg1 = args[1].(*v1.IPReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IPServiceClient_Modified_Call) Return(empty *v1.Empty, err error) *IPServiceClient_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *IPServiceClient_Modified_Call) RunAndReturn(run func(ctx context.Context, in *v1.IPReport, opts ...grpc.CallOption) (*v1.Empty, error)) *IPServiceClient_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Usage(ctx context.Context, in *v1.IPUsageRequest, opts ...grpc.CallOption) (*v1.IPUsageResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.IPUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPUsageRequest, ...grpc.CallOption) (*v1.IPUsageResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPUsageRequest, ...grpc.CallOption) *v1.IPUsageResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.IPUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPUsageRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type IPServiceClient_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.IPUsageRequest
//   - opts ...grpc.CallOption
func (_e *IPServiceClient_Expecter) Usage(ctx any, in any, opts ...any) *IPServiceClient_Usage_Call {
	return &IPServiceClient_Usage_Call{Call: _e.mock.On("Usage",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *IPServiceClient_Usage_Call) Run(run func(ctx context.Context, in *v1.IPUsageRequest, opts ...grpc.CallOption)) *IPServiceClient_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.IPUsageRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IPServiceClient_Usage_Call) Return(iPUsageResponse *v1.IPUsageResponse, err error) *IPServiceClient_Usage_Call {
	_c.Call.Return(iPUsageResponse, err)
	return _c
}

func (_c *IPServiceClient_Usage_Call) RunAndReturn(run func(ctx context.Context, in *v1.IPUsageRequest, opts ...grpc.CallOption) (*v1.IPUsageResponse, error)) *IPServiceClient_Usage_Call {
	_c.Call.Return(run)
	return _c
}
