// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewIPServiceServer creates a new instance of IPServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPServiceServer {
	mock := &IPServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IPServiceServer is an autogenerated mock type for the IPServiceServer type
type IPServiceServer struct {
	mock.Mock
}

type IPServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *IPServiceServer) EXPECT() *IPServiceServer_Expecter {
	return &IPServiceServer_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type IPServiceServer
func (_mock *IPServiceServer) Added(context1 context.Context, iPReport *v1.IPReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, iPReport)

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, iPReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport) *v1.Empty); ok {
		r0 = returnFunc(context1, iPReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPReport) error); ok {
		r1 = returnFunc(context1, iPReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceServer_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type IPServiceServer_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - context1 context.Context
//   - iPReport *v1.IPReport
func (_e *IPServiceServer_Expecter) Added(context1 any, iPReport any) *IPServiceServer_Added_Call {
	return &IPServiceServer_Added_Call{Call: _e.mock.On("Added", context1, iPReport)}
}

func (_c *IPServiceServer_Added_Call) Run(run func(context1 context.Context, iPReport *v1.IPReport)) *IPServiceServer_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPReport
		if args[1] != nil {
			arg1 = args[1].(*v1.IPReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceServer_Added_Call) Return(empty *v1.Empty, err error) *IPServiceServer_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *IPServiceServer_Added_Call) RunAndReturn(run func(context1 context.Context, iPReport *v1.IPReport) (*v1.Empty, error)) *IPServiceServer_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type IPServiceServer
func (_mock *IPServiceServer) Deleted(context1 context.Context, iPReport *v1.IPReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, iPReport)

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, iPReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport) *v1.Empty); ok {
		r0 = returnFunc(context1, iPReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPReport) error); ok {
		r1 = returnFunc(context1, iPReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceServer_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type IPServiceServer_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - context1 context.Context
//   - iPReport *v1.IPReport
func (_e *IPServiceServer_Expecter) Deleted(context1 any, iPReport any) *IPServiceServer_Deleted_Call {
	return &IPServiceServer_Deleted_Call{Call: _e.mock.On("Deleted", context1, iPReport)}
}

func (_c *IPServiceServer_Deleted_Call) Run(run func(context1 context.Context, iPReport *v1.IPReport)) *IPServiceServer_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPReport
		if args[1] != nil {
			arg1 = args[1].(*v1.IPReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceServer_Deleted_Call) Return(empty *v1.Empty, err error) *IPServiceServer_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *IPServiceServer_Deleted_Call) RunAndReturn(run func(context1 context.Context, iPReport *v1.IPReport) (*v1.Empty, error)) *IPServiceServer_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type IPServiceServer
func (_mock *IPServiceServer) Modified(context1 context.Context, iPReport *v1.IPReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, iPReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, iPReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPReport) *v1.Empty); ok {
		r0 = returnFunc(context1, iPReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPReport) error); ok {
		r1 = returnFunc(context1, iPReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type IPServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - iPReport *v1.IPReport
func (_e *IPServiceServer_Expecter) Modified(context1 any, iPReport any) *IPServiceServer_Modified_Call {
	return &IPServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, iPReport)}
}

func (_c *IPServiceServer_Modified_Call) Run(run func(context1 context.Context, iPReport *v1.IPReport)) *IPServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPReport
		if args[1] != nil {
			arg1 = args[1].(*v1.IPReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceServer_Modified_Call) Return(empty *v1.Empty, err error) *IPServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *IPServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, iPReport *v1.IPReport) (*v1.Empty, error)) *IPServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type IPServiceServer
func (_mock *IPServiceServer) Usage(context1 context.Context, iPUsageRequest *v1.IPUsageRequest) (*v1.IPUsageResponse, error) {
	ret := _mock.Called(context1, iPUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.IPUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPUsageRequest) (*v1.IPUsageResponse, error)); ok {
		return returnFunc(context1, iPUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.IPUsageRequest) *v1.IPUsageResponse); ok {
		r0 = returnFunc(context1, iPUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.IPUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.IPUsageRequest) error); ok {
		r1 = returnFunc(context1, iPUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type IPServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - iPUsageRequest *v1.IPUsageRequest
func (_e *IPServiceServer_Expecter) Usage(context1 any, iPUsageRequest any) *IPServiceServer_Usage_Call {
	return &IPServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, iPUsageRequest)}
}

func (_c *IPServiceServer_Usage_Call) Run(run func(context1 context.Context, iPUsageRequest *v1.IPUsageRequest)) *IPServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.IPUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.IPUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceServer_Usage_Call) Return(iPUsageResponse *v1.IPUsageResponse, err error) *IPServiceServer_Usage_Call {
	_c.Call.Return(iPUsageResponse, err)
	return _c
}

func (_c *IPServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, iPUsageRequest *v1.IPUsageRequest) (*v1.IPUsageResponse, error)) *IPServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
