// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMachineServiceServer creates a new instance of MachineServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMachineServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MachineServiceServer {
	mock := &MachineServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MachineServiceServer is an autogenerated mock type for the MachineServiceServer type
type MachineServiceServer struct {
	mock.Mock
}

type MachineServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MachineServiceServer) EXPECT() *MachineServiceServer_Expecter {
	return &MachineServiceServer_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type MachineServiceServer
func (_mock *MachineServiceServer) Added(context1 context.Context, machineReport *v1.MachineReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, machineReport)

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, machineReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReport) *v1.Empty); ok {
		r0 = returnFunc(context1, machineReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineReport) error); ok {
		r1 = returnFunc(context1, machineReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineServiceServer_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type MachineServiceServer_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - context1 context.Context
//   - machineReport *v1.MachineReport
func (_e *MachineServiceServer_Expecter) Added(context1 any, machineReport any) *MachineServiceServer_Added_Call {
	return &MachineServiceServer_Added_Call{Call: _e.mock.On("Added", context1, machineReport)}
}

func (_c *MachineServiceServer_Added_Call) Run(run func(context1 context.Context, machineReport *v1.MachineReport)) *MachineServiceServer_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineReport
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineServiceServer_Added_Call) Return(empty *v1.Empty, err error) *MachineServiceServer_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MachineServiceServer_Added_Call) RunAndReturn(run func(context1 context.Context, machineReport *v1.MachineReport) (*v1.Empty, error)) *MachineServiceServer_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type MachineServiceServer
func (_mock *MachineServiceServer) Deleted(context1 context.Context, machineReport *v1.MachineReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, machineReport)

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, machineReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReport) *v1.Empty); ok {
		r0 = returnFunc(context1, machineReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineReport) error); ok {
		r1 = returnFunc(context1, machineReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineServiceServer_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type MachineServiceServer_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - context1 context.Context
//   - machineReport *v1.MachineReport
func (_e *MachineServiceServer_Expecter) Deleted(context1 any, machineReport any) *MachineServiceServer_Deleted_Call {
	return &MachineServiceServer_Deleted_Call{Call: _e.mock.On("Deleted", context1, machineReport)}
}

func (_c *MachineServiceServer_Deleted_Call) Run(run func(context1 context.Context, machineReport *v1.MachineReport)) *MachineServiceServer_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineReport
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineServiceServer_Deleted_Call) Return(empty *v1.Empty, err error) *MachineServiceServer_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MachineServiceServer_Deleted_Call) RunAndReturn(run func(context1 context.Context, machineReport *v1.MachineReport) (*v1.Empty, error)) *MachineServiceServer_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type MachineServiceServer
func (_mock *MachineServiceServer) Modified(context1 context.Context, machineReport *v1.MachineReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, machineReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, machineReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineReport) *v1.Empty); ok {
		r0 = returnFunc(context1, machineReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineReport) error); ok {
		r1 = returnFunc(context1, machineReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type MachineServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - machineReport *v1.MachineReport
func (_e *MachineServiceServer_Expecter) Modified(context1 any, machineReport any) *MachineServiceServer_Modified_Call {
	return &MachineServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, machineReport)}
}

func (_c *MachineServiceServer_Modified_Call) Run(run func(context1 context.Context, machineReport *v1.MachineReport)) *MachineServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineReport
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineServiceServer_Modified_Call) Return(empty *v1.Empty, err error) *MachineServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MachineServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, machineReport *v1.MachineReport) (*v1.Empty, error)) *MachineServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MachineServiceServer
func (_mock *MachineServiceServer) Usage(context1 context.Context, machineUsageRequest *v1.MachineUsageRequest) (*v1.MachineUsageResponse, error) {
	ret := _mock.Called(context1, machineUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.MachineUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineUsageRequest) (*v1.MachineUsageResponse, error)); ok {
		return returnFunc(context1, machineUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.MachineUsageRequest) *v1.MachineUsageResponse); ok {
		r0 = returnFunc(context1, machineUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.MachineUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.MachineUsageRequest) error); ok {
		r1 = returnFunc(context1, machineUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MachineServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - machineUsageRequest *v1.MachineUsageRequest
func (_e *MachineServiceServer_Expecter) Usage(context1 any, machineUsageRequest any) *MachineServiceServer_Usage_Call {
	return &MachineServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, machineUsageRequest)}
}

func (_c *MachineServiceServer_Usage_Call) Run(run func(context1 context.Context, machineUsageRequest *v1.MachineUsageRequest)) *MachineServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.MachineUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.MachineUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineServiceServer_Usage_Call) Return(machineUsageResponse *v1.MachineUsageResponse, err error) *MachineServiceServer_Usage_Call {
	_c.Call.Return(machineUsageResponse, err)
	return _c
}

func (_c *MachineServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, machineUsageRequest *v1.MachineUsageRequest) (*v1.MachineUsageResponse, error)) *MachineServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
