// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewNetworkTrafficServiceClient creates a new instance of NetworkTrafficServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetworkTrafficServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetworkTrafficServiceClient {
	mock := &NetworkTrafficServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NetworkTrafficServiceClient is an autogenerated mock type for the NetworkTrafficServiceClient type
type NetworkTrafficServiceClient struct {
	mock.Mock
}

type NetworkTrafficServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *NetworkTrafficServiceClient) EXPECT() *NetworkTrafficServiceClient_Expecter {
	return &NetworkTrafficServiceClient_Expecter{mock: &_m.Mock}
}

// Modified provides a mock function for the type NetworkTrafficServiceClient
func (_mock *NetworkTrafficServiceClient) Modified(ctx context.Context, in *v1.NetworkTrafficReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkTrafficReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkTrafficReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.NetworkTrafficReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkTrafficServiceClient_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type NetworkTrafficServiceClient_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.NetworkTrafficReport
//   - opts ...grpc.CallOption
func (_e *NetworkTrafficServiceClient_Expecter) Modified(ctx any, in any, opts ...any) *NetworkTrafficServiceClient_Modified_Call {
	return &NetworkTrafficServiceClient_Modified_Call{Call: _e.mock.On("Modified",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *NetworkTrafficServiceClient_Modified_Call) Run(run func(ctx context.Context, in *v1.NetworkTrafficReport, opts ...grpc.CallOption)) *NetworkTrafficServiceClient_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.NetworkTrafficReport
		if args[1] != nil {
			arg1 = args[1].(*v1.NetworkTrafficReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *NetworkTrafficServiceClient_Modified_Call) Return(empty *v1.Empty, err error) *NetworkTrafficServiceClient_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *NetworkTrafficServiceClient_Modified_Call) RunAndReturn(run func(ctx context.Context, in *v1.NetworkTrafficReport, opts ...grpc.CallOption) (*v1.Empty, error)) *NetworkTrafficServiceClient_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type NetworkTrafficServiceClient
func (_mock *NetworkTrafficServiceClient) Usage(ctx context.Context, in *v1.NetworkUsageRequest, opts ...grpc.CallOption) (*v1.NetworkUsageResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.NetworkUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkUsageRequest, ...grpc.CallOption) (*v1.NetworkUsageResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.NetworkUsageRequest, ...grpc.CallOption) *v1.NetworkUsageResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.NetworkUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.NetworkUsageRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetworkTrafficServiceClient_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type NetworkTrafficServiceClient_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.NetworkUsageRequest
//   - opts ...grpc.CallOption
func (_e *NetworkTrafficServiceClient_Expecter) Usage(ctx any, in any, opts ...any) *NetworkTrafficServiceClient_Usage_Call {
	return &NetworkTrafficServiceClient_Usage_Call{Call: _e.mock.On("Usage",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *NetworkTrafficServiceClient_Usage_Call) Run(run func(ctx context.Context, in *v1.NetworkUsageRequest, opts ...grpc.CallOption)) *NetworkTrafficServiceClient_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.NetworkUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.NetworkUsageRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *NetworkTrafficServiceClient_Usage_Call) Return(networkUsageResponse *v1.NetworkUsageResponse, err error) *NetworkTrafficServiceClient_Usage_Call {
	_c.Call.Return(networkUsageResponse, err)
	return _c
}

func (_c *NetworkTrafficServiceClient_Usage_Call) RunAndReturn(run func(ctx context.Context, in *v1.NetworkUsageRequest, opts ...grpc.CallOption) (*v1.NetworkUsageResponse, error)) *NetworkTrafficServiceClient_Usage_Call {
	_c.Call.Return(run)
	return _c
}
