// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewPostgresServiceClient creates a new instance of PostgresServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgresServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostgresServiceClient {
	mock := &PostgresServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PostgresServiceClient is an autogenerated mock type for the PostgresServiceClient type
type PostgresServiceClient struct {
	mock.Mock
}

type PostgresServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PostgresServiceClient) EXPECT() *PostgresServiceClient_Expecter {
	return &PostgresServiceClient_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type PostgresServiceClient
func (_mock *PostgresServiceClient) Added(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresServiceClient_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type PostgresServiceClient_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.PostgresReport
//   - opts ...grpc.CallOption
func (_e *PostgresServiceClient_Expecter) Added(ctx any, in any, opts ...any) *PostgresServiceClient_Added_Call {
	return &PostgresServiceClient_Added_Call{Call: _e.mock.On("Added",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *PostgresServiceClient_Added_Call) Run(run func(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption)) *PostgresServiceClient_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.PostgresReport
		if args[1] != nil {
			arg1 = args[1].(*v1.PostgresReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *PostgresServiceClient_Added_Call) Return(empty *v1.Empty, err error) *PostgresServiceClient_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *PostgresServiceClient_Added_Call) RunAndReturn(run func(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption) (*v1.Empty, error)) *PostgresServiceClient_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type PostgresServiceClient
func (_mock *PostgresServiceClient) Deleted(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresServiceClient_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type PostgresServiceClient_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.PostgresReport
//   - opts ...grpc.CallOption
func (_e *PostgresServiceClient_Expecter) Deleted(ctx any, in any, opts ...any) *PostgresServiceClient_Deleted_Call {
	return &PostgresServiceClient_Deleted_Call{Call: _e.mock.On("Deleted",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *PostgresServiceClient_Deleted_Call) Run(run func(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption)) *PostgresServiceClient_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.PostgresReport
		if args[1] != nil {
			arg1 = args[1].(*v1.PostgresReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *PostgresServiceClient_Deleted_Call) Return(empty *v1.Empty, err error) *PostgresServiceClient_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *PostgresServiceClient_Deleted_Call) RunAndReturn(run func(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption) (*v1.Empty, error)) *PostgresServiceClient_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type PostgresServiceClient
func (_mock *PostgresServiceClient) Modified(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.PostgresReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresServiceClient_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type PostgresServiceClient_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.PostgresReport
//   - opts ...grpc.CallOption
func (_e *PostgresServiceClient_Expecter) Modified(ctx any, in any, opts ...any) *PostgresServiceClient_Modified_Call {
	return &PostgresServiceClient_Modified_Call{Call: _e.mock.On("Modified",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *PostgresServiceClient_Modified_Call) Run(run func(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption)) *PostgresServiceClient_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.PostgresReport
		if args[1] != nil {
			arg1 = args[1].(*v1.PostgresReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *PostgresServiceClient_Modified_Call) Return(empty *v1.Empty, err error) *PostgresServiceClient_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *PostgresServiceClient_Modified_Call) RunAndReturn(run func(ctx context.Context, in *v1.PostgresReport, opts ...grpc.CallOption) (*v1.Empty, error)) *PostgresServiceClient_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type PostgresServiceClient
func (_mock *PostgresServiceClient) Usage(ctx context.Context, in *v1.PostgresUsageRequest, opts ...grpc.CallOption) (*v1.PostgresUsageResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.PostgresUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresUsageRequest, ...grpc.CallOption) (*v1.PostgresUsageResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.PostgresUsageRequest, ...grpc.CallOption) *v1.PostgresUsageResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PostgresUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.PostgresUsageRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresServiceClient_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type PostgresServiceClient_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.PostgresUsageRequest
//   - opts ...grpc.CallOption
func (_e *PostgresServiceClient_Expecter) Usage(ctx any, in any, opts ...any) *PostgresServiceClient_Usage_Call {
	return &PostgresServiceClient_Usage_Call{Call: _e.mock.On("Usage",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *PostgresServiceClient_Usage_Call) Run(run func(ctx context.Context, in *v1.PostgresUsageRequest, opts ...grpc.CallOption)) *PostgresServiceClient_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.PostgresUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.PostgresUsageRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *PostgresServiceClient_Usage_Call) Return(postgresUsageResponse *v1.PostgresUsageResponse, err error) *PostgresServiceClient_Usage_Call {
	_c.Call.Return(postgresUsageResponse, err)
	return _c
}

func (_c *PostgresServiceClient_Usage_Call) RunAndReturn(run func(ctx context.Context, in *v1.PostgresUsageRequest, opts ...grpc.CallOption) (*v1.PostgresUsageResponse, error)) *PostgresServiceClient_Usage_Call {
	_c.Call.Return(run)
	return _c
}
