// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	v1 "github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// ProductOptionServiceServer is an autogenerated mock type for the ProductOptionServiceServer type
type ProductOptionServiceServer struct {
	mock.Mock
}

// Modified provides a mock function with given fields: _a0, _a1
func (_m *ProductOptionServiceServer) Modified(_a0 context.Context, _a1 *v1.ProductOptionReport) (*v1.Empty, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionReport) (*v1.Empty, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionReport) *v1.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ProductOptionReport) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Usage provides a mock function with given fields: _a0, _a1
func (_m *ProductOptionServiceServer) Usage(_a0 context.Context, _a1 *v1.ProductOptionUsageRequest) (*v1.ProductOptionUsageResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.ProductOptionUsageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionUsageRequest) (*v1.ProductOptionUsageResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionUsageRequest) *v1.ProductOptionUsageResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProductOptionUsageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ProductOptionUsageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductOptionServiceServer creates a new instance of ProductOptionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductOptionServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductOptionServiceServer {
	mock := &ProductOptionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
