// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewProductOptionServiceServer creates a new instance of ProductOptionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductOptionServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductOptionServiceServer {
	mock := &ProductOptionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductOptionServiceServer is an autogenerated mock type for the ProductOptionServiceServer type
type ProductOptionServiceServer struct {
	mock.Mock
}

type ProductOptionServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductOptionServiceServer) EXPECT() *ProductOptionServiceServer_Expecter {
	return &ProductOptionServiceServer_Expecter{mock: &_m.Mock}
}

// Modified provides a mock function for the type ProductOptionServiceServer
func (_mock *ProductOptionServiceServer) Modified(context1 context.Context, productOptionReport *v1.ProductOptionReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, productOptionReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, productOptionReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionReport) *v1.Empty); ok {
		r0 = returnFunc(context1, productOptionReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ProductOptionReport) error); ok {
		r1 = returnFunc(context1, productOptionReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductOptionServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type ProductOptionServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - productOptionReport *v1.ProductOptionReport
func (_e *ProductOptionServiceServer_Expecter) Modified(context1 any, productOptionReport any) *ProductOptionServiceServer_Modified_Call {
	return &ProductOptionServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, productOptionReport)}
}

func (_c *ProductOptionServiceServer_Modified_Call) Run(run func(context1 context.Context, productOptionReport *v1.ProductOptionReport)) *ProductOptionServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ProductOptionReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ProductOptionReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductOptionServiceServer_Modified_Call) Return(empty *v1.Empty, err error) *ProductOptionServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ProductOptionServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, productOptionReport *v1.ProductOptionReport) (*v1.Empty, error)) *ProductOptionServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type ProductOptionServiceServer
func (_mock *ProductOptionServiceServer) Usage(context1 context.Context, productOptionUsageRequest *v1.ProductOptionUsageRequest) (*v1.ProductOptionUsageResponse, error) {
	ret := _mock.Called(context1, productOptionUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.ProductOptionUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionUsageRequest) (*v1.ProductOptionUsageResponse, error)); ok {
		return returnFunc(context1, productOptionUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProductOptionUsageRequest) *v1.ProductOptionUsageResponse); ok {
		r0 = returnFunc(context1, productOptionUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProductOptionUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ProductOptionUsageRequest) error); ok {
		r1 = returnFunc(context1, productOptionUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductOptionServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type ProductOptionServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - productOptionUsageRequest *v1.ProductOptionUsageRequest
func (_e *ProductOptionServiceServer_Expecter) Usage(context1 any, productOptionUsageRequest any) *ProductOptionServiceServer_Usage_Call {
	return &ProductOptionServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, productOptionUsageRequest)}
}

func (_c *ProductOptionServiceServer_Usage_Call) Run(run func(context1 context.Context, productOptionUsageRequest *v1.ProductOptionUsageRequest)) *ProductOptionServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ProductOptionUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ProductOptionUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductOptionServiceServer_Usage_Call) Return(productOptionUsageResponse *v1.ProductOptionUsageResponse, err error) *ProductOptionServiceServer_Usage_Call {
	_c.Call.Return(productOptionUsageResponse, err)
	return _c
}

func (_c *ProductOptionServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, productOptionUsageRequest *v1.ProductOptionUsageRequest) (*v1.ProductOptionUsageResponse, error)) *ProductOptionServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
