// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewS3ServiceClient creates a new instance of S3ServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3ServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3ServiceClient {
	mock := &S3ServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// S3ServiceClient is an autogenerated mock type for the S3ServiceClient type
type S3ServiceClient struct {
	mock.Mock
}

type S3ServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *S3ServiceClient) EXPECT() *S3ServiceClient_Expecter {
	return &S3ServiceClient_Expecter{mock: &_m.Mock}
}

// BucketStats provides a mock function for the type S3ServiceClient
func (_mock *S3ServiceClient) BucketStats(ctx context.Context, in *v1.S3BucketReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BucketStats")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.S3BucketReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.S3BucketReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.S3BucketReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ServiceClient_BucketStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketStats'
type S3ServiceClient_BucketStats_Call struct {
	*mock.Call
}

// BucketStats is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.S3BucketReport
//   - opts ...grpc.CallOption
func (_e *S3ServiceClient_Expecter) BucketStats(ctx any, in any, opts ...any) *S3ServiceClient_BucketStats_Call {
	return &S3ServiceClient_BucketStats_Call{Call: _e.mock.On("BucketStats",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *S3ServiceClient_BucketStats_Call) Run(run func(ctx context.Context, in *v1.S3BucketReport, opts ...grpc.CallOption)) *S3ServiceClient_BucketStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.S3BucketReport
		if args[1] != nil {
			arg1 = args[1].(*v1.S3BucketReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ServiceClient_BucketStats_Call) Return(empty *v1.Empty, err error) *S3ServiceClient_BucketStats_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *S3ServiceClient_BucketStats_Call) RunAndReturn(run func(ctx context.Context, in *v1.S3BucketReport, opts ...grpc.CallOption) (*v1.Empty, error)) *S3ServiceClient_BucketStats_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type S3ServiceClient
func (_mock *S3ServiceClient) Usage(ctx context.Context, in *v1.S3UsageRequest, opts ...grpc.CallOption) (*v1.S3UsageResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.S3UsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.S3UsageRequest, ...grpc.CallOption) (*v1.S3UsageResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.S3UsageRequest, ...grpc.CallOption) *v1.S3UsageResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3UsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.S3UsageRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ServiceClient_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type S3ServiceClient_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.S3UsageRequest
//   - opts ...grpc.CallOption
func (_e *S3ServiceClient_Expecter) Usage(ctx any, in any, opts ...any) *S3ServiceClient_Usage_Call {
	return &S3ServiceClient_Usage_Call{Call: _e.mock.On("Usage",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *S3ServiceClient_Usage_Call) Run(run func(ctx context.Context, in *v1.S3UsageRequest, opts ...grpc.CallOption)) *S3ServiceClient_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.S3UsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.S3UsageRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ServiceClient_Usage_Call) Return(s3UsageResponse *v1.S3UsageResponse, err error) *S3ServiceClient_Usage_Call {
	_c.Call.Return(s3UsageResponse, err)
	return _c
}

func (_c *S3ServiceClient_Usage_Call) RunAndReturn(run func(ctx context.Context, in *v1.S3UsageRequest, opts ...grpc.CallOption) (*v1.S3UsageResponse, error)) *S3ServiceClient_Usage_Call {
	_c.Call.Return(run)
	return _c
}
