// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnsafeVolumeServiceServer creates a new instance of UnsafeVolumeServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeVolumeServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeVolumeServiceServer {
	mock := &UnsafeVolumeServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnsafeVolumeServiceServer is an autogenerated mock type for the UnsafeVolumeServiceServer type
type UnsafeVolumeServiceServer struct {
	mock.Mock
}

type UnsafeVolumeServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeVolumeServiceServer) EXPECT() *UnsafeVolumeServiceServer_Expecter {
	return &UnsafeVolumeServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedVolumeServiceServer provides a mock function for the type UnsafeVolumeServiceServer
func (_mock *UnsafeVolumeServiceServer) mustEmbedUnimplementedVolumeServiceServer() {
	_mock.Called()
	return
}

// UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedVolumeServiceServer'
type UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedVolumeServiceServer is a helper method to define mock.On call
func (_e *UnsafeVolumeServiceServer_Expecter) mustEmbedUnimplementedVolumeServiceServer() *UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	return &UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedVolumeServiceServer")}
}

func (_c *UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) Run(run func()) *UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) Return() *UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) RunAndReturn(run func()) *UnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Run(run)
	return _c
}
