// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeIPServiceServer is an autogenerated mock type for the UnsafeIPServiceServer type
type UnsafeIPServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedIPServiceServer provides a mock function with no fields
func (_m *UnsafeIPServiceServer) mustEmbedUnimplementedIPServiceServer() {
	_m.Called()
}

// NewUnsafeIPServiceServer creates a new instance of UnsafeIPServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeIPServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeIPServiceServer {
	mock := &UnsafeIPServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
