// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeMachineReservationServiceServer is an autogenerated mock type for the UnsafeMachineReservationServiceServer type
type UnsafeMachineReservationServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedMachineReservationServiceServer provides a mock function with no fields
func (_m *UnsafeMachineReservationServiceServer) mustEmbedUnimplementedMachineReservationServiceServer() {
	_m.Called()
}

// NewUnsafeMachineReservationServiceServer creates a new instance of UnsafeMachineReservationServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeMachineReservationServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeMachineReservationServiceServer {
	mock := &UnsafeMachineReservationServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
