// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnsafeMachineReservationServiceServer creates a new instance of UnsafeMachineReservationServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeMachineReservationServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeMachineReservationServiceServer {
	mock := &UnsafeMachineReservationServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnsafeMachineReservationServiceServer is an autogenerated mock type for the UnsafeMachineReservationServiceServer type
type UnsafeMachineReservationServiceServer struct {
	mock.Mock
}

type UnsafeMachineReservationServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeMachineReservationServiceServer) EXPECT() *UnsafeMachineReservationServiceServer_Expecter {
	return &UnsafeMachineReservationServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedMachineReservationServiceServer provides a mock function for the type UnsafeMachineReservationServiceServer
func (_mock *UnsafeMachineReservationServiceServer) mustEmbedUnimplementedMachineReservationServiceServer() {
	_mock.Called()
	return
}

// UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedMachineReservationServiceServer'
type UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedMachineReservationServiceServer is a helper method to define mock.On call
func (_e *UnsafeMachineReservationServiceServer_Expecter) mustEmbedUnimplementedMachineReservationServiceServer() *UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call {
	return &UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedMachineReservationServiceServer")}
}

func (_c *UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call) Run(run func()) *UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call) Return() *UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call) RunAndReturn(run func()) *UnsafeMachineReservationServiceServer_mustEmbedUnimplementedMachineReservationServiceServer_Call {
	_c.Run(run)
	return _c
}
