// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnsafeProductOptionServiceServer creates a new instance of UnsafeProductOptionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeProductOptionServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeProductOptionServiceServer {
	mock := &UnsafeProductOptionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnsafeProductOptionServiceServer is an autogenerated mock type for the UnsafeProductOptionServiceServer type
type UnsafeProductOptionServiceServer struct {
	mock.Mock
}

type UnsafeProductOptionServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeProductOptionServiceServer) EXPECT() *UnsafeProductOptionServiceServer_Expecter {
	return &UnsafeProductOptionServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedProductOptionServiceServer provides a mock function for the type UnsafeProductOptionServiceServer
func (_mock *UnsafeProductOptionServiceServer) mustEmbedUnimplementedProductOptionServiceServer() {
	_mock.Called()
	return
}

// UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedProductOptionServiceServer'
type UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedProductOptionServiceServer is a helper method to define mock.On call
func (_e *UnsafeProductOptionServiceServer_Expecter) mustEmbedUnimplementedProductOptionServiceServer() *UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call {
	return &UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedProductOptionServiceServer")}
}

func (_c *UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call) Run(run func()) *UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call) Return() *UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call) RunAndReturn(run func()) *UnsafeProductOptionServiceServer_mustEmbedUnimplementedProductOptionServiceServer_Call {
	_c.Run(run)
	return _c
}
