// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnsafePodServiceServer creates a new instance of UnsafePodServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafePodServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafePodServiceServer {
	mock := &UnsafePodServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnsafePodServiceServer is an autogenerated mock type for the UnsafePodServiceServer type
type UnsafePodServiceServer struct {
	mock.Mock
}

type UnsafePodServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafePodServiceServer) EXPECT() *UnsafePodServiceServer_Expecter {
	return &UnsafePodServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedPodServiceServer provides a mock function for the type UnsafePodServiceServer
func (_mock *UnsafePodServiceServer) mustEmbedUnimplementedPodServiceServer() {
	_mock.Called()
	return
}

// UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedPodServiceServer'
type UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedPodServiceServer is a helper method to define mock.On call
func (_e *UnsafePodServiceServer_Expecter) mustEmbedUnimplementedPodServiceServer() *UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call {
	return &UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedPodServiceServer")}
}

func (_c *UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call) Run(run func()) *UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call) Return() *UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call) RunAndReturn(run func()) *UnsafePodServiceServer_mustEmbedUnimplementedPodServiceServer_Call {
	_c.Run(run)
	return _c
}
