// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnsafeClusterServiceServer creates a new instance of UnsafeClusterServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeClusterServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeClusterServiceServer {
	mock := &UnsafeClusterServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnsafeClusterServiceServer is an autogenerated mock type for the UnsafeClusterServiceServer type
type UnsafeClusterServiceServer struct {
	mock.Mock
}

type UnsafeClusterServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeClusterServiceServer) EXPECT() *UnsafeClusterServiceServer_Expecter {
	return &UnsafeClusterServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedClusterServiceServer provides a mock function for the type UnsafeClusterServiceServer
func (_mock *UnsafeClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {
	_mock.Called()
	return
}

// UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedClusterServiceServer'
type UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedClusterServiceServer is a helper method to define mock.On call
func (_e *UnsafeClusterServiceServer_Expecter) mustEmbedUnimplementedClusterServiceServer() *UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	return &UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedClusterServiceServer")}
}

func (_c *UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call) Run(run func()) *UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call) Return() *UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call) RunAndReturn(run func()) *UnsafeClusterServiceServer_mustEmbedUnimplementedClusterServiceServer_Call {
	_c.Run(run)
	return _c
}
