// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewVolumeServiceServer creates a new instance of VolumeServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVolumeServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *VolumeServiceServer {
	mock := &VolumeServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VolumeServiceServer is an autogenerated mock type for the VolumeServiceServer type
type VolumeServiceServer struct {
	mock.Mock
}

type VolumeServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *VolumeServiceServer) EXPECT() *VolumeServiceServer_Expecter {
	return &VolumeServiceServer_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type VolumeServiceServer
func (_mock *VolumeServiceServer) Added(context1 context.Context, volumeReport *v1.VolumeReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, volumeReport)

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, volumeReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport) *v1.Empty); ok {
		r0 = returnFunc(context1, volumeReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeReport) error); ok {
		r1 = returnFunc(context1, volumeReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceServer_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type VolumeServiceServer_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - context1 context.Context
//   - volumeReport *v1.VolumeReport
func (_e *VolumeServiceServer_Expecter) Added(context1 any, volumeReport any) *VolumeServiceServer_Added_Call {
	return &VolumeServiceServer_Added_Call{Call: _e.mock.On("Added", context1, volumeReport)}
}

func (_c *VolumeServiceServer_Added_Call) Run(run func(context1 context.Context, volumeReport *v1.VolumeReport)) *VolumeServiceServer_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeReport
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VolumeServiceServer_Added_Call) Return(empty *v1.Empty, err error) *VolumeServiceServer_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *VolumeServiceServer_Added_Call) RunAndReturn(run func(context1 context.Context, volumeReport *v1.VolumeReport) (*v1.Empty, error)) *VolumeServiceServer_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type VolumeServiceServer
func (_mock *VolumeServiceServer) Deleted(context1 context.Context, volumeReport *v1.VolumeReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, volumeReport)

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, volumeReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport) *v1.Empty); ok {
		r0 = returnFunc(context1, volumeReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeReport) error); ok {
		r1 = returnFunc(context1, volumeReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceServer_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type VolumeServiceServer_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - context1 context.Context
//   - volumeReport *v1.VolumeReport
func (_e *VolumeServiceServer_Expecter) Deleted(context1 any, volumeReport any) *VolumeServiceServer_Deleted_Call {
	return &VolumeServiceServer_Deleted_Call{Call: _e.mock.On("Deleted", context1, volumeReport)}
}

func (_c *VolumeServiceServer_Deleted_Call) Run(run func(context1 context.Context, volumeReport *v1.VolumeReport)) *VolumeServiceServer_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeReport
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VolumeServiceServer_Deleted_Call) Return(empty *v1.Empty, err error) *VolumeServiceServer_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *VolumeServiceServer_Deleted_Call) RunAndReturn(run func(context1 context.Context, volumeReport *v1.VolumeReport) (*v1.Empty, error)) *VolumeServiceServer_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type VolumeServiceServer
func (_mock *VolumeServiceServer) Modified(context1 context.Context, volumeReport *v1.VolumeReport) (*v1.Empty, error) {
	ret := _mock.Called(context1, volumeReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v1.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport) (*v1.Empty, error)); ok {
		return returnFunc(context1, volumeReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeReport) *v1.Empty); ok {
		r0 = returnFunc(context1, volumeReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeReport) error); ok {
		r1 = returnFunc(context1, volumeReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type VolumeServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - volumeReport *v1.VolumeReport
func (_e *VolumeServiceServer_Expecter) Modified(context1 any, volumeReport any) *VolumeServiceServer_Modified_Call {
	return &VolumeServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, volumeReport)}
}

func (_c *VolumeServiceServer_Modified_Call) Run(run func(context1 context.Context, volumeReport *v1.VolumeReport)) *VolumeServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeReport
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VolumeServiceServer_Modified_Call) Return(empty *v1.Empty, err error) *VolumeServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *VolumeServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, volumeReport *v1.VolumeReport) (*v1.Empty, error)) *VolumeServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type VolumeServiceServer
func (_mock *VolumeServiceServer) Usage(context1 context.Context, volumeUsageRequest *v1.VolumeUsageRequest) (*v1.VolumeUsageResponse, error) {
	ret := _mock.Called(context1, volumeUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.VolumeUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeUsageRequest) (*v1.VolumeUsageResponse, error)); ok {
		return returnFunc(context1, volumeUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.VolumeUsageRequest) *v1.VolumeUsageResponse); ok {
		r0 = returnFunc(context1, volumeUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.VolumeUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.VolumeUsageRequest) error); ok {
		r1 = returnFunc(context1, volumeUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VolumeServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type VolumeServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - volumeUsageRequest *v1.VolumeUsageRequest
func (_e *VolumeServiceServer_Expecter) Usage(context1 any, volumeUsageRequest any) *VolumeServiceServer_Usage_Call {
	return &VolumeServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, volumeUsageRequest)}
}

func (_c *VolumeServiceServer_Usage_Call) Run(run func(context1 context.Context, volumeUsageRequest *v1.VolumeUsageRequest)) *VolumeServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.VolumeUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.VolumeUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VolumeServiceServer_Usage_Call) Return(volumeUsageResponse *v1.VolumeUsageResponse, err error) *VolumeServiceServer_Usage_Call {
	_c.Call.Return(volumeUsageResponse, err)
	return _c
}

func (_c *VolumeServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, volumeUsageRequest *v1.VolumeUsageRequest) (*v1.VolumeUsageResponse, error)) *VolumeServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
