// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	v10 "github.com/fi-ts/accounting-go/pkg/apis/v1"
	"github.com/fi-ts/accounting-go/pkg/apis/vm/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewManagedVMServiceServer creates a new instance of ManagedVMServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagedVMServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagedVMServiceServer {
	mock := &ManagedVMServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ManagedVMServiceServer is an autogenerated mock type for the ManagedVMServiceServer type
type ManagedVMServiceServer struct {
	mock.Mock
}

type ManagedVMServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *ManagedVMServiceServer) EXPECT() *ManagedVMServiceServer_Expecter {
	return &ManagedVMServiceServer_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type ManagedVMServiceServer
func (_mock *ManagedVMServiceServer) Added(context1 context.Context, managedVMReport *v1.ManagedVMReport) (*v10.Empty, error) {
	ret := _mock.Called(context1, managedVMReport)

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v10.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport) (*v10.Empty, error)); ok {
		return returnFunc(context1, managedVMReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport) *v10.Empty); ok {
		r0 = returnFunc(context1, managedVMReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMReport) error); ok {
		r1 = returnFunc(context1, managedVMReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceServer_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type ManagedVMServiceServer_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - context1 context.Context
//   - managedVMReport *v1.ManagedVMReport
func (_e *ManagedVMServiceServer_Expecter) Added(context1 any, managedVMReport any) *ManagedVMServiceServer_Added_Call {
	return &ManagedVMServiceServer_Added_Call{Call: _e.mock.On("Added", context1, managedVMReport)}
}

func (_c *ManagedVMServiceServer_Added_Call) Run(run func(context1 context.Context, managedVMReport *v1.ManagedVMReport)) *ManagedVMServiceServer_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ManagedVMServiceServer_Added_Call) Return(empty *v10.Empty, err error) *ManagedVMServiceServer_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ManagedVMServiceServer_Added_Call) RunAndReturn(run func(context1 context.Context, managedVMReport *v1.ManagedVMReport) (*v10.Empty, error)) *ManagedVMServiceServer_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type ManagedVMServiceServer
func (_mock *ManagedVMServiceServer) Deleted(context1 context.Context, managedVMReport *v1.ManagedVMReport) (*v10.Empty, error) {
	ret := _mock.Called(context1, managedVMReport)

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v10.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport) (*v10.Empty, error)); ok {
		return returnFunc(context1, managedVMReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport) *v10.Empty); ok {
		r0 = returnFunc(context1, managedVMReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMReport) error); ok {
		r1 = returnFunc(context1, managedVMReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceServer_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type ManagedVMServiceServer_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - context1 context.Context
//   - managedVMReport *v1.ManagedVMReport
func (_e *ManagedVMServiceServer_Expecter) Deleted(context1 any, managedVMReport any) *ManagedVMServiceServer_Deleted_Call {
	return &ManagedVMServiceServer_Deleted_Call{Call: _e.mock.On("Deleted", context1, managedVMReport)}
}

func (_c *ManagedVMServiceServer_Deleted_Call) Run(run func(context1 context.Context, managedVMReport *v1.ManagedVMReport)) *ManagedVMServiceServer_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ManagedVMServiceServer_Deleted_Call) Return(empty *v10.Empty, err error) *ManagedVMServiceServer_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ManagedVMServiceServer_Deleted_Call) RunAndReturn(run func(context1 context.Context, managedVMReport *v1.ManagedVMReport) (*v10.Empty, error)) *ManagedVMServiceServer_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type ManagedVMServiceServer
func (_mock *ManagedVMServiceServer) Modified(context1 context.Context, managedVMReport *v1.ManagedVMReport) (*v10.Empty, error) {
	ret := _mock.Called(context1, managedVMReport)

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v10.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport) (*v10.Empty, error)); ok {
		return returnFunc(context1, managedVMReport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport) *v10.Empty); ok {
		r0 = returnFunc(context1, managedVMReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMReport) error); ok {
		r1 = returnFunc(context1, managedVMReport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceServer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type ManagedVMServiceServer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - context1 context.Context
//   - managedVMReport *v1.ManagedVMReport
func (_e *ManagedVMServiceServer_Expecter) Modified(context1 any, managedVMReport any) *ManagedVMServiceServer_Modified_Call {
	return &ManagedVMServiceServer_Modified_Call{Call: _e.mock.On("Modified", context1, managedVMReport)}
}

func (_c *ManagedVMServiceServer_Modified_Call) Run(run func(context1 context.Context, managedVMReport *v1.ManagedVMReport)) *ManagedVMServiceServer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMReport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ManagedVMServiceServer_Modified_Call) Return(empty *v10.Empty, err error) *ManagedVMServiceServer_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ManagedVMServiceServer_Modified_Call) RunAndReturn(run func(context1 context.Context, managedVMReport *v1.ManagedVMReport) (*v10.Empty, error)) *ManagedVMServiceServer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type ManagedVMServiceServer
func (_mock *ManagedVMServiceServer) Usage(context1 context.Context, managedVMUsageRequest *v1.ManagedVMUsageRequest) (*v1.ManagedVMUsageResponse, error) {
	ret := _mock.Called(context1, managedVMUsageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.ManagedVMUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMUsageRequest) (*v1.ManagedVMUsageResponse, error)); ok {
		return returnFunc(context1, managedVMUsageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMUsageRequest) *v1.ManagedVMUsageResponse); ok {
		r0 = returnFunc(context1, managedVMUsageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ManagedVMUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMUsageRequest) error); ok {
		r1 = returnFunc(context1, managedVMUsageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceServer_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type ManagedVMServiceServer_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - context1 context.Context
//   - managedVMUsageRequest *v1.ManagedVMUsageRequest
func (_e *ManagedVMServiceServer_Expecter) Usage(context1 any, managedVMUsageRequest any) *ManagedVMServiceServer_Usage_Call {
	return &ManagedVMServiceServer_Usage_Call{Call: _e.mock.On("Usage", context1, managedVMUsageRequest)}
}

func (_c *ManagedVMServiceServer_Usage_Call) Run(run func(context1 context.Context, managedVMUsageRequest *v1.ManagedVMUsageRequest)) *ManagedVMServiceServer_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMUsageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ManagedVMServiceServer_Usage_Call) Return(managedVMUsageResponse *v1.ManagedVMUsageResponse, err error) *ManagedVMServiceServer_Usage_Call {
	_c.Call.Return(managedVMUsageResponse, err)
	return _c
}

func (_c *ManagedVMServiceServer_Usage_Call) RunAndReturn(run func(context1 context.Context, managedVMUsageRequest *v1.ManagedVMUsageRequest) (*v1.ManagedVMUsageResponse, error)) *ManagedVMServiceServer_Usage_Call {
	_c.Call.Return(run)
	return _c
}
