// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: fits/api/vm/v1/managed_vm.proto

package v1

import (
	v1 "github.com/fi-ts/accounting-go/pkg/apis/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManagedVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Fqdname       string                 `protobuf:"bytes,3,opt,name=fqdname,proto3" json:"fqdname,omitempty"`
	Cpus          string                 `protobuf:"bytes,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory        string                 `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Volumes       []*ManagedVMVolume     `protobuf:"bytes,7,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedVM) Reset() {
	*x = ManagedVM{}
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedVM) ProtoMessage() {}

func (x *ManagedVM) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedVM.ProtoReflect.Descriptor instead.
func (*ManagedVM) Descriptor() ([]byte, []int) {
	return file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedVM) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ManagedVM) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ManagedVM) GetFqdname() string {
	if x != nil {
		return x.Fqdname
	}
	return ""
}

func (x *ManagedVM) GetCpus() string {
	if x != nil {
		return x.Cpus
	}
	return ""
}

func (x *ManagedVM) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ManagedVM) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ManagedVM) GetVolumes() []*ManagedVMVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type ManagedVMVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	StorageType   string                 `protobuf:"bytes,3,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedVMVolume) Reset() {
	*x = ManagedVMVolume{}
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedVMVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedVMVolume) ProtoMessage() {}

func (x *ManagedVMVolume) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedVMVolume.ProtoReflect.Descriptor instead.
func (*ManagedVMVolume) Descriptor() ([]byte, []int) {
	return file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP(), []int{1}
}

func (x *ManagedVMVolume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagedVMVolume) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ManagedVMVolume) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *ManagedVMVolume) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ManagedVMReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Projectid     string                 `protobuf:"bytes,2,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Requestid     string                 `protobuf:"bytes,3,opt,name=requestid,proto3" json:"requestid,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Vm            *ManagedVM             `protobuf:"bytes,7,opt,name=vm,proto3" json:"vm,omitempty"`
	Annotations   []string               `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedVMReport) Reset() {
	*x = ManagedVMReport{}
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedVMReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedVMReport) ProtoMessage() {}

func (x *ManagedVMReport) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedVMReport.ProtoReflect.Descriptor instead.
func (*ManagedVMReport) Descriptor() ([]byte, []int) {
	return file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP(), []int{2}
}

func (x *ManagedVMReport) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ManagedVMReport) GetProjectid() string {
	if x != nil {
		return x.Projectid
	}
	return ""
}

func (x *ManagedVMReport) GetRequestid() string {
	if x != nil {
		return x.Requestid
	}
	return ""
}

func (x *ManagedVMReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ManagedVMReport) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ManagedVMReport) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ManagedVMReport) GetVm() *ManagedVM {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *ManagedVMReport) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ManagedVMUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Tenant        *string                `protobuf:"bytes,3,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	Projectid     *string                `protobuf:"bytes,4,opt,name=projectid,proto3,oneof" json:"projectid,omitempty"`
	Annotations   []string               `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedVMUsageRequest) Reset() {
	*x = ManagedVMUsageRequest{}
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedVMUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedVMUsageRequest) ProtoMessage() {}

func (x *ManagedVMUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedVMUsageRequest.ProtoReflect.Descriptor instead.
func (*ManagedVMUsageRequest) Descriptor() ([]byte, []int) {
	return file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP(), []int{3}
}

func (x *ManagedVMUsageRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ManagedVMUsageRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ManagedVMUsageRequest) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

func (x *ManagedVMUsageRequest) GetProjectid() string {
	if x != nil && x.Projectid != nil {
		return *x.Projectid
	}
	return ""
}

func (x *ManagedVMUsageRequest) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ManagedVMUsageResponse struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	From             *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Usage            []*ManagedVMUsage           `protobuf:"bytes,3,rep,name=usage,proto3" json:"usage,omitempty"`
	AccumulatedUsage *ManagedVMUsageAccumuluated `protobuf:"bytes,4,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ManagedVMUsageResponse) Reset() {
	*x = ManagedVMUsageResponse{}
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedVMUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedVMUsageResponse) ProtoMessage() {}

func (x *ManagedVMUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedVMUsageResponse.ProtoReflect.Descriptor instead.
func (*ManagedVMUsageResponse) Descriptor() ([]byte, []int) {
	return file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP(), []int{4}
}

func (x *ManagedVMUsageResponse) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ManagedVMUsageResponse) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ManagedVMUsageResponse) GetUsage() []*ManagedVMUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ManagedVMUsageResponse) GetAccumulatedUsage() *ManagedVMUsageAccumuluated {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

type ManagedVMUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Fqdname       string                 `protobuf:"bytes,3,opt,name=fqdname,proto3" json:"fqdname,omitempty"`
	VmStart       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=vm_start,json=vmStart,proto3" json:"vm_start,omitempty"`
	VmEnd         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=vm_end,json=vmEnd,proto3" json:"vm_end,omitempty"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,6,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	CpuSeconds    string                 `protobuf:"bytes,7,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	MemorySeconds string                 `protobuf:"bytes,8,opt,name=memory_seconds,json=memorySeconds,proto3" json:"memory_seconds,omitempty"`
	Warnings      []string               `protobuf:"bytes,9,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Annotations   []string               `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Tenant        string                 `protobuf:"bytes,11,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ProjectId     string                 `protobuf:"bytes,12,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,13,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	RequestId     string                 `protobuf:"bytes,14,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Volumes       []*ManagedVMVolume     `protobuf:"bytes,15,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedVMUsage) Reset() {
	*x = ManagedVMUsage{}
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedVMUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedVMUsage) ProtoMessage() {}

func (x *ManagedVMUsage) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedVMUsage.ProtoReflect.Descriptor instead.
func (*ManagedVMUsage) Descriptor() ([]byte, []int) {
	return file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP(), []int{5}
}

func (x *ManagedVMUsage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ManagedVMUsage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ManagedVMUsage) GetFqdname() string {
	if x != nil {
		return x.Fqdname
	}
	return ""
}

func (x *ManagedVMUsage) GetVmStart() *timestamppb.Timestamp {
	if x != nil {
		return x.VmStart
	}
	return nil
}

func (x *ManagedVMUsage) GetVmEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.VmEnd
	}
	return nil
}

func (x *ManagedVMUsage) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *ManagedVMUsage) GetCpuSeconds() string {
	if x != nil {
		return x.CpuSeconds
	}
	return ""
}

func (x *ManagedVMUsage) GetMemorySeconds() string {
	if x != nil {
		return x.MemorySeconds
	}
	return ""
}

func (x *ManagedVMUsage) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ManagedVMUsage) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ManagedVMUsage) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ManagedVMUsage) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ManagedVMUsage) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ManagedVMUsage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ManagedVMUsage) GetVolumes() []*ManagedVMVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type ManagedVMUsageAccumuluated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	CpuSeconds    string                 `protobuf:"bytes,2,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	MemorySeconds string                 `protobuf:"bytes,3,opt,name=memory_seconds,json=memorySeconds,proto3" json:"memory_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedVMUsageAccumuluated) Reset() {
	*x = ManagedVMUsageAccumuluated{}
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedVMUsageAccumuluated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedVMUsageAccumuluated) ProtoMessage() {}

func (x *ManagedVMUsageAccumuluated) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_vm_v1_managed_vm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedVMUsageAccumuluated.ProtoReflect.Descriptor instead.
func (*ManagedVMUsageAccumuluated) Descriptor() ([]byte, []int) {
	return file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP(), []int{6}
}

func (x *ManagedVMUsageAccumuluated) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *ManagedVMUsageAccumuluated) GetCpuSeconds() string {
	if x != nil {
		return x.CpuSeconds
	}
	return ""
}

func (x *ManagedVMUsageAccumuluated) GetMemorySeconds() string {
	if x != nil {
		return x.MemorySeconds
	}
	return ""
}

var File_fits_api_vm_v1_managed_vm_proto protoreflect.FileDescriptor

const file_fits_api_vm_v1_managed_vm_proto_rawDesc = "" +
	"\n" +
	"\x1ffits/api/vm/v1/managed_vm.proto\x12\x0efits.api.vm.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,metalstack/io/accounting/api/v1/common.proto\"\xd2\x01\n" +
	"\tManagedVM\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\afqdname\x18\x03 \x01(\tR\afqdname\x12\x12\n" +
	"\x04cpus\x18\x04 \x01(\tR\x04cpus\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\tR\x06memory\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x129\n" +
	"\avolumes\x18\a \x03(\v2\x1f.fits.api.vm.v1.ManagedVMVolumeR\avolumes\"p\n" +
	"\x0fManagedVMVolume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12!\n" +
	"\fstorage_type\x18\x03 \x01(\tR\vstorageType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\"\xde\x02\n" +
	"\x0fManagedVMReport\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tprojectid\x18\x02 \x01(\tR\tprojectid\x12\x1c\n" +
	"\trequestid\x18\x03 \x01(\tR\trequestid\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12)\n" +
	"\x02vm\x18\a \x01(\v2\x19.fits.api.vm.v1.ManagedVMR\x02vm\x12 \n" +
	"\vannotations\x18\b \x03(\tR\vannotations\"\xee\x01\n" +
	"\x15ManagedVMUsageRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1b\n" +
	"\x06tenant\x18\x03 \x01(\tH\x00R\x06tenant\x88\x01\x01\x12!\n" +
	"\tprojectid\x18\x04 \x01(\tH\x01R\tprojectid\x88\x01\x01\x12 \n" +
	"\vannotations\x18\x05 \x03(\tR\vannotationsB\t\n" +
	"\a_tenantB\f\n" +
	"\n" +
	"_projectid\"\x83\x02\n" +
	"\x16ManagedVMUsageResponse\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x124\n" +
	"\x05usage\x18\x03 \x03(\v2\x1e.fits.api.vm.v1.ManagedVMUsageR\x05usage\x12W\n" +
	"\x11accumulated_usage\x18\x04 \x01(\v2*.fits.api.vm.v1.ManagedVMUsageAccumuluatedR\x10accumulatedUsage\"\xb5\x04\n" +
	"\x0eManagedVMUsage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\afqdname\x18\x03 \x01(\tR\afqdname\x125\n" +
	"\bvm_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\avmStart\x121\n" +
	"\x06vm_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05vmEnd\x125\n" +
	"\blifetime\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1f\n" +
	"\vcpu_seconds\x18\a \x01(\tR\n" +
	"cpuSeconds\x12%\n" +
	"\x0ememory_seconds\x18\b \x01(\tR\rmemorySeconds\x12\x1a\n" +
	"\bwarnings\x18\t \x03(\tR\bwarnings\x12 \n" +
	"\vannotations\x18\n" +
	" \x03(\tR\vannotations\x12\x16\n" +
	"\x06tenant\x18\v \x01(\tR\x06tenant\x12\x1d\n" +
	"\n" +
	"project_id\x18\f \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\r \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x0e \x01(\tR\trequestId\x129\n" +
	"\avolumes\x18\x0f \x03(\v2\x1f.fits.api.vm.v1.ManagedVMVolumeR\avolumes\"\x9b\x01\n" +
	"\x1aManagedVMUsageAccumuluated\x125\n" +
	"\blifetime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1f\n" +
	"\vcpu_seconds\x18\x02 \x01(\tR\n" +
	"cpuSeconds\x12%\n" +
	"\x0ememory_seconds\x18\x03 \x01(\tR\rmemorySeconds2\xe5\x02\n" +
	"\x10ManagedVMService\x12P\n" +
	"\x05Added\x12\x1f.fits.api.vm.v1.ManagedVMReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12S\n" +
	"\bModified\x12\x1f.fits.api.vm.v1.ManagedVMReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12R\n" +
	"\aDeleted\x12\x1f.fits.api.vm.v1.ManagedVMReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12V\n" +
	"\x05Usage\x12%.fits.api.vm.v1.ManagedVMUsageRequest\x1a&.fits.api.vm.v1.ManagedVMUsageResponseB\x10Z\x0epkg/apis/vm/v1b\x06proto3"

var (
	file_fits_api_vm_v1_managed_vm_proto_rawDescOnce sync.Once
	file_fits_api_vm_v1_managed_vm_proto_rawDescData []byte
)

func file_fits_api_vm_v1_managed_vm_proto_rawDescGZIP() []byte {
	file_fits_api_vm_v1_managed_vm_proto_rawDescOnce.Do(func() {
		file_fits_api_vm_v1_managed_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fits_api_vm_v1_managed_vm_proto_rawDesc), len(file_fits_api_vm_v1_managed_vm_proto_rawDesc)))
	})
	return file_fits_api_vm_v1_managed_vm_proto_rawDescData
}

var file_fits_api_vm_v1_managed_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fits_api_vm_v1_managed_vm_proto_goTypes = []any{
	(*ManagedVM)(nil),                  // 0: fits.api.vm.v1.ManagedVM
	(*ManagedVMVolume)(nil),            // 1: fits.api.vm.v1.ManagedVMVolume
	(*ManagedVMReport)(nil),            // 2: fits.api.vm.v1.ManagedVMReport
	(*ManagedVMUsageRequest)(nil),      // 3: fits.api.vm.v1.ManagedVMUsageRequest
	(*ManagedVMUsageResponse)(nil),     // 4: fits.api.vm.v1.ManagedVMUsageResponse
	(*ManagedVMUsage)(nil),             // 5: fits.api.vm.v1.ManagedVMUsage
	(*ManagedVMUsageAccumuluated)(nil), // 6: fits.api.vm.v1.ManagedVMUsageAccumuluated
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 8: google.protobuf.Duration
	(*v1.Empty)(nil),                   // 9: metalstack.io.accounting.api.v1.Empty
}
var file_fits_api_vm_v1_managed_vm_proto_depIdxs = []int32{
	1,  // 0: fits.api.vm.v1.ManagedVM.volumes:type_name -> fits.api.vm.v1.ManagedVMVolume
	7,  // 1: fits.api.vm.v1.ManagedVMReport.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 2: fits.api.vm.v1.ManagedVMReport.start_date:type_name -> google.protobuf.Timestamp
	7,  // 3: fits.api.vm.v1.ManagedVMReport.end_date:type_name -> google.protobuf.Timestamp
	0,  // 4: fits.api.vm.v1.ManagedVMReport.vm:type_name -> fits.api.vm.v1.ManagedVM
	7,  // 5: fits.api.vm.v1.ManagedVMUsageRequest.from:type_name -> google.protobuf.Timestamp
	7,  // 6: fits.api.vm.v1.ManagedVMUsageRequest.to:type_name -> google.protobuf.Timestamp
	7,  // 7: fits.api.vm.v1.ManagedVMUsageResponse.from:type_name -> google.protobuf.Timestamp
	7,  // 8: fits.api.vm.v1.ManagedVMUsageResponse.to:type_name -> google.protobuf.Timestamp
	5,  // 9: fits.api.vm.v1.ManagedVMUsageResponse.usage:type_name -> fits.api.vm.v1.ManagedVMUsage
	6,  // 10: fits.api.vm.v1.ManagedVMUsageResponse.accumulated_usage:type_name -> fits.api.vm.v1.ManagedVMUsageAccumuluated
	7,  // 11: fits.api.vm.v1.ManagedVMUsage.vm_start:type_name -> google.protobuf.Timestamp
	7,  // 12: fits.api.vm.v1.ManagedVMUsage.vm_end:type_name -> google.protobuf.Timestamp
	8,  // 13: fits.api.vm.v1.ManagedVMUsage.lifetime:type_name -> google.protobuf.Duration
	1,  // 14: fits.api.vm.v1.ManagedVMUsage.volumes:type_name -> fits.api.vm.v1.ManagedVMVolume
	8,  // 15: fits.api.vm.v1.ManagedVMUsageAccumuluated.lifetime:type_name -> google.protobuf.Duration
	2,  // 16: fits.api.vm.v1.ManagedVMService.Added:input_type -> fits.api.vm.v1.ManagedVMReport
	2,  // 17: fits.api.vm.v1.ManagedVMService.Modified:input_type -> fits.api.vm.v1.ManagedVMReport
	2,  // 18: fits.api.vm.v1.ManagedVMService.Deleted:input_type -> fits.api.vm.v1.ManagedVMReport
	3,  // 19: fits.api.vm.v1.ManagedVMService.Usage:input_type -> fits.api.vm.v1.ManagedVMUsageRequest
	9,  // 20: fits.api.vm.v1.ManagedVMService.Added:output_type -> metalstack.io.accounting.api.v1.Empty
	9,  // 21: fits.api.vm.v1.ManagedVMService.Modified:output_type -> metalstack.io.accounting.api.v1.Empty
	9,  // 22: fits.api.vm.v1.ManagedVMService.Deleted:output_type -> metalstack.io.accounting.api.v1.Empty
	4,  // 23: fits.api.vm.v1.ManagedVMService.Usage:output_type -> fits.api.vm.v1.ManagedVMUsageResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_fits_api_vm_v1_managed_vm_proto_init() }
func file_fits_api_vm_v1_managed_vm_proto_init() {
	if File_fits_api_vm_v1_managed_vm_proto != nil {
		return
	}
	file_fits_api_vm_v1_managed_vm_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fits_api_vm_v1_managed_vm_proto_rawDesc), len(file_fits_api_vm_v1_managed_vm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fits_api_vm_v1_managed_vm_proto_goTypes,
		DependencyIndexes: file_fits_api_vm_v1_managed_vm_proto_depIdxs,
		MessageInfos:      file_fits_api_vm_v1_managed_vm_proto_msgTypes,
	}.Build()
	File_fits_api_vm_v1_managed_vm_proto = out.File
	file_fits_api_vm_v1_managed_vm_proto_goTypes = nil
	file_fits_api_vm_v1_managed_vm_proto_depIdxs = nil
}
