// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metalstack/io/accounting/api/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_common_proto_rawDescGZIP(), []int{0}
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Projectid     string                 `protobuf:"bytes,3,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Clusterid     string                 `protobuf:"bytes,4,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	Clustername   string                 `protobuf:"bytes,5,opt,name=clustername,proto3" json:"clustername,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Projectname   string                 `protobuf:"bytes,7,opt,name=projectname,proto3" json:"projectname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Report) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *Report) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Report) GetProjectid() string {
	if x != nil {
		return x.Projectid
	}
	return ""
}

func (x *Report) GetClusterid() string {
	if x != nil {
		return x.Clusterid
	}
	return ""
}

func (x *Report) GetClustername() string {
	if x != nil {
		return x.Clustername
	}
	return ""
}

func (x *Report) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Report) GetProjectname() string {
	if x != nil {
		return x.Projectname
	}
	return ""
}

type KubernetesResourceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesResourceReport) Reset() {
	*x = KubernetesResourceReport{}
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesResourceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesResourceReport) ProtoMessage() {}

func (x *KubernetesResourceReport) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesResourceReport.ProtoReflect.Descriptor instead.
func (*KubernetesResourceReport) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesResourceReport) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *KubernetesResourceReport) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesResourceReport) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *KubernetesResourceReport) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type UsageQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Tenant        *string                `protobuf:"bytes,3,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	Projectid     *string                `protobuf:"bytes,4,opt,name=projectid,proto3,oneof" json:"projectid,omitempty"`
	Clusterid     *string                `protobuf:"bytes,5,opt,name=clusterid,proto3,oneof" json:"clusterid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageQuery) Reset() {
	*x = UsageQuery{}
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageQuery) ProtoMessage() {}

func (x *UsageQuery) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageQuery.ProtoReflect.Descriptor instead.
func (*UsageQuery) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *UsageQuery) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *UsageQuery) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *UsageQuery) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

func (x *UsageQuery) GetProjectid() string {
	if x != nil && x.Projectid != nil {
		return *x.Projectid
	}
	return ""
}

func (x *UsageQuery) GetClusterid() string {
	if x != nil && x.Clusterid != nil {
		return *x.Clusterid
	}
	return ""
}

var File_metalstack_io_accounting_api_v1_common_proto protoreflect.FileDescriptor

const file_metalstack_io_accounting_api_v1_common_proto_rawDesc = "" +
	"\n" +
	",metalstack/io/accounting/api/v1/common.proto\x12\x1fmetalstack.io.accounting.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xf8\x01\n" +
	"\x06Report\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tprojectid\x18\x03 \x01(\tR\tprojectid\x12\x1c\n" +
	"\tclusterid\x18\x04 \x01(\tR\tclusterid\x12 \n" +
	"\vclustername\x18\x05 \x01(\tR\vclustername\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\vprojectname\x18\a \x01(\tR\vprojectname\"\xeb\x01\n" +
	"\x18KubernetesResourceReport\x12?\n" +
	"\x06report\x18\x01 \x01(\v2'.metalstack.io.accounting.api.v1.ReportR\x06report\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xf2\x01\n" +
	"\n" +
	"UsageQuery\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1b\n" +
	"\x06tenant\x18\x03 \x01(\tH\x00R\x06tenant\x88\x01\x01\x12!\n" +
	"\tprojectid\x18\x04 \x01(\tH\x01R\tprojectid\x88\x01\x01\x12!\n" +
	"\tclusterid\x18\x05 \x01(\tH\x02R\tclusterid\x88\x01\x01B\t\n" +
	"\a_tenantB\f\n" +
	"\n" +
	"_projectidB\f\n" +
	"\n" +
	"_clusteridB\rZ\vpkg/apis/v1b\x06proto3"

var (
	file_metalstack_io_accounting_api_v1_common_proto_rawDescOnce sync.Once
	file_metalstack_io_accounting_api_v1_common_proto_rawDescData []byte
)

func file_metalstack_io_accounting_api_v1_common_proto_rawDescGZIP() []byte {
	file_metalstack_io_accounting_api_v1_common_proto_rawDescOnce.Do(func() {
		file_metalstack_io_accounting_api_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_common_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_common_proto_rawDesc)))
	})
	return file_metalstack_io_accounting_api_v1_common_proto_rawDescData
}

var file_metalstack_io_accounting_api_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metalstack_io_accounting_api_v1_common_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: metalstack.io.accounting.api.v1.Empty
	(*Report)(nil),                   // 1: metalstack.io.accounting.api.v1.Report
	(*KubernetesResourceReport)(nil), // 2: metalstack.io.accounting.api.v1.KubernetesResourceReport
	(*UsageQuery)(nil),               // 3: metalstack.io.accounting.api.v1.UsageQuery
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_metalstack_io_accounting_api_v1_common_proto_depIdxs = []int32{
	4, // 0: metalstack.io.accounting.api.v1.Report.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: metalstack.io.accounting.api.v1.KubernetesResourceReport.report:type_name -> metalstack.io.accounting.api.v1.Report
	4, // 2: metalstack.io.accounting.api.v1.KubernetesResourceReport.start_date:type_name -> google.protobuf.Timestamp
	4, // 3: metalstack.io.accounting.api.v1.KubernetesResourceReport.end_date:type_name -> google.protobuf.Timestamp
	4, // 4: metalstack.io.accounting.api.v1.UsageQuery.from:type_name -> google.protobuf.Timestamp
	4, // 5: metalstack.io.accounting.api.v1.UsageQuery.to:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_metalstack_io_accounting_api_v1_common_proto_init() }
func file_metalstack_io_accounting_api_v1_common_proto_init() {
	if File_metalstack_io_accounting_api_v1_common_proto != nil {
		return
	}
	file_metalstack_io_accounting_api_v1_common_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_common_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metalstack_io_accounting_api_v1_common_proto_goTypes,
		DependencyIndexes: file_metalstack_io_accounting_api_v1_common_proto_depIdxs,
		MessageInfos:      file_metalstack_io_accounting_api_v1_common_proto_msgTypes,
	}.Build()
	File_metalstack_io_accounting_api_v1_common_proto = out.File
	file_metalstack_io_accounting_api_v1_common_proto_goTypes = nil
	file_metalstack_io_accounting_api_v1_common_proto_depIdxs = nil
}
