// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metalstack/io/accounting/api/v1/ip.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Projectid     string                 `protobuf:"bytes,3,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	Annotations   []string               `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Projectname   string                 `protobuf:"bytes,8,opt,name=projectname,proto3" json:"projectname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IP) Reset() {
	*x = IP{}
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_ip_proto_rawDescGZIP(), []int{0}
}

func (x *IP) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IP) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *IP) GetProjectid() string {
	if x != nil {
		return x.Projectid
	}
	return ""
}

func (x *IP) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *IP) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *IP) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *IP) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *IP) GetProjectname() string {
	if x != nil {
		return x.Projectname
	}
	return ""
}

type IPReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ips           []*IP                  `protobuf:"bytes,5,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPReport) Reset() {
	*x = IPReport{}
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPReport) ProtoMessage() {}

func (x *IPReport) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPReport.ProtoReflect.Descriptor instead.
func (*IPReport) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_ip_proto_rawDescGZIP(), []int{1}
}

func (x *IPReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IPReport) GetIps() []*IP {
	if x != nil {
		return x.Ips
	}
	return nil
}

type IPUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Tenant        *string                `protobuf:"bytes,3,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	Projectid     *string                `protobuf:"bytes,4,opt,name=projectid,proto3,oneof" json:"projectid,omitempty"`
	Annotations   []string               `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPUsageRequest) Reset() {
	*x = IPUsageRequest{}
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPUsageRequest) ProtoMessage() {}

func (x *IPUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPUsageRequest.ProtoReflect.Descriptor instead.
func (*IPUsageRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_ip_proto_rawDescGZIP(), []int{2}
}

func (x *IPUsageRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *IPUsageRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *IPUsageRequest) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

func (x *IPUsageRequest) GetProjectid() string {
	if x != nil && x.Projectid != nil {
		return *x.Projectid
	}
	return ""
}

func (x *IPUsageRequest) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type IPUsageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	From             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Usage            []*IPUsage             `protobuf:"bytes,3,rep,name=usage,proto3" json:"usage,omitempty"`
	AccumulatedUsage *IPUsageAccumuluated   `protobuf:"bytes,4,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IPUsageResponse) Reset() {
	*x = IPUsageResponse{}
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPUsageResponse) ProtoMessage() {}

func (x *IPUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPUsageResponse.ProtoReflect.Descriptor instead.
func (*IPUsageResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_ip_proto_rawDescGZIP(), []int{3}
}

func (x *IPUsageResponse) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *IPUsageResponse) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *IPUsageResponse) GetUsage() []*IPUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *IPUsageResponse) GetAccumulatedUsage() *IPUsageAccumuluated {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

type IPUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tenant         string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Projectid      string                 `protobuf:"bytes,2,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Ip             string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	IpStart        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ip_start,json=ipStart,proto3" json:"ip_start,omitempty"`
	IpEnd          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ip_end,json=ipEnd,proto3" json:"ip_end,omitempty"`
	Lifetime       *durationpb.Duration   `protobuf:"bytes,6,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	Warnings       []string               `protobuf:"bytes,7,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Uuid           string                 `protobuf:"bytes,8,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Projectname    string                 `protobuf:"bytes,9,opt,name=projectname,proto3" json:"projectname,omitempty"`
	Annotations    []string               `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Tenantname     string                 `protobuf:"bytes,11,opt,name=tenantname,proto3" json:"tenantname,omitempty"`
	Contractnumber string                 `protobuf:"bytes,12,opt,name=contractnumber,proto3" json:"contractnumber,omitempty"`
	Debtorid       string                 `protobuf:"bytes,13,opt,name=debtorid,proto3" json:"debtorid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IPUsage) Reset() {
	*x = IPUsage{}
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPUsage) ProtoMessage() {}

func (x *IPUsage) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPUsage.ProtoReflect.Descriptor instead.
func (*IPUsage) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_ip_proto_rawDescGZIP(), []int{4}
}

func (x *IPUsage) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *IPUsage) GetProjectid() string {
	if x != nil {
		return x.Projectid
	}
	return ""
}

func (x *IPUsage) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPUsage) GetIpStart() *timestamppb.Timestamp {
	if x != nil {
		return x.IpStart
	}
	return nil
}

func (x *IPUsage) GetIpEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.IpEnd
	}
	return nil
}

func (x *IPUsage) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *IPUsage) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *IPUsage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *IPUsage) GetProjectname() string {
	if x != nil {
		return x.Projectname
	}
	return ""
}

func (x *IPUsage) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *IPUsage) GetTenantname() string {
	if x != nil {
		return x.Tenantname
	}
	return ""
}

func (x *IPUsage) GetContractnumber() string {
	if x != nil {
		return x.Contractnumber
	}
	return ""
}

func (x *IPUsage) GetDebtorid() string {
	if x != nil {
		return x.Debtorid
	}
	return ""
}

type IPUsageAccumuluated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPUsageAccumuluated) Reset() {
	*x = IPUsageAccumuluated{}
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPUsageAccumuluated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPUsageAccumuluated) ProtoMessage() {}

func (x *IPUsageAccumuluated) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPUsageAccumuluated.ProtoReflect.Descriptor instead.
func (*IPUsageAccumuluated) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_ip_proto_rawDescGZIP(), []int{5}
}

func (x *IPUsageAccumuluated) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

var File_metalstack_io_accounting_api_v1_ip_proto protoreflect.FileDescriptor

const file_metalstack_io_accounting_api_v1_ip_proto_rawDesc = "" +
	"\n" +
	"(metalstack/io/accounting/api/v1/ip.proto\x12\x1fmetalstack.io.accounting.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,metalstack/io/accounting/api/v1/common.proto\"\x8c\x02\n" +
	"\x02IP\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tprojectid\x18\x03 \x01(\tR\tprojectid\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x120\n" +
	"\x05start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12 \n" +
	"\vannotations\x18\a \x03(\tR\vannotations\x12 \n" +
	"\vprojectname\x18\b \x01(\tR\vprojectname\"{\n" +
	"\bIPReport\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\x03ips\x18\x05 \x03(\v2#.metalstack.io.accounting.api.v1.IPR\x03ips\"\xe7\x01\n" +
	"\x0eIPUsageRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1b\n" +
	"\x06tenant\x18\x03 \x01(\tH\x00R\x06tenant\x88\x01\x01\x12!\n" +
	"\tprojectid\x18\x04 \x01(\tH\x01R\tprojectid\x88\x01\x01\x12 \n" +
	"\vannotations\x18\x05 \x03(\tR\vannotationsB\t\n" +
	"\a_tenantB\f\n" +
	"\n" +
	"_projectid\"\x90\x02\n" +
	"\x0fIPUsageResponse\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12>\n" +
	"\x05usage\x18\x03 \x03(\v2(.metalstack.io.accounting.api.v1.IPUsageR\x05usage\x12a\n" +
	"\x11accumulated_usage\x18\x04 \x01(\v24.metalstack.io.accounting.api.v1.IPUsageAccumuluatedR\x10accumulatedUsage\"\xc8\x03\n" +
	"\aIPUsage\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tprojectid\x18\x02 \x01(\tR\tprojectid\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x125\n" +
	"\bip_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aipStart\x121\n" +
	"\x06ip_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05ipEnd\x125\n" +
	"\blifetime\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1a\n" +
	"\bwarnings\x18\a \x03(\tR\bwarnings\x12\x12\n" +
	"\x04uuid\x18\b \x01(\tR\x04uuid\x12 \n" +
	"\vprojectname\x18\t \x01(\tR\vprojectname\x12 \n" +
	"\vannotations\x18\n" +
	" \x03(\tR\vannotations\x12\x1e\n" +
	"\n" +
	"tenantname\x18\v \x01(\tR\n" +
	"tenantname\x12&\n" +
	"\x0econtractnumber\x18\f \x01(\tR\x0econtractnumber\x12\x1a\n" +
	"\bdebtorid\x18\r \x01(\tR\bdebtorid\"L\n" +
	"\x13IPUsageAccumuluated\x125\n" +
	"\blifetime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\blifetime2\x90\x03\n" +
	"\tIPService\x12Z\n" +
	"\x05Added\x12).metalstack.io.accounting.api.v1.IPReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12]\n" +
	"\bModified\x12).metalstack.io.accounting.api.v1.IPReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12\\\n" +
	"\aDeleted\x12).metalstack.io.accounting.api.v1.IPReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12j\n" +
	"\x05Usage\x12/.metalstack.io.accounting.api.v1.IPUsageRequest\x1a0.metalstack.io.accounting.api.v1.IPUsageResponseB\rZ\vpkg/apis/v1b\x06proto3"

var (
	file_metalstack_io_accounting_api_v1_ip_proto_rawDescOnce sync.Once
	file_metalstack_io_accounting_api_v1_ip_proto_rawDescData []byte
)

func file_metalstack_io_accounting_api_v1_ip_proto_rawDescGZIP() []byte {
	file_metalstack_io_accounting_api_v1_ip_proto_rawDescOnce.Do(func() {
		file_metalstack_io_accounting_api_v1_ip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_ip_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_ip_proto_rawDesc)))
	})
	return file_metalstack_io_accounting_api_v1_ip_proto_rawDescData
}

var file_metalstack_io_accounting_api_v1_ip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metalstack_io_accounting_api_v1_ip_proto_goTypes = []any{
	(*IP)(nil),                    // 0: metalstack.io.accounting.api.v1.IP
	(*IPReport)(nil),              // 1: metalstack.io.accounting.api.v1.IPReport
	(*IPUsageRequest)(nil),        // 2: metalstack.io.accounting.api.v1.IPUsageRequest
	(*IPUsageResponse)(nil),       // 3: metalstack.io.accounting.api.v1.IPUsageResponse
	(*IPUsage)(nil),               // 4: metalstack.io.accounting.api.v1.IPUsage
	(*IPUsageAccumuluated)(nil),   // 5: metalstack.io.accounting.api.v1.IPUsageAccumuluated
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
	(*Empty)(nil),                 // 8: metalstack.io.accounting.api.v1.Empty
}
var file_metalstack_io_accounting_api_v1_ip_proto_depIdxs = []int32{
	6,  // 0: metalstack.io.accounting.api.v1.IP.start:type_name -> google.protobuf.Timestamp
	6,  // 1: metalstack.io.accounting.api.v1.IP.end:type_name -> google.protobuf.Timestamp
	6,  // 2: metalstack.io.accounting.api.v1.IPReport.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: metalstack.io.accounting.api.v1.IPReport.ips:type_name -> metalstack.io.accounting.api.v1.IP
	6,  // 4: metalstack.io.accounting.api.v1.IPUsageRequest.from:type_name -> google.protobuf.Timestamp
	6,  // 5: metalstack.io.accounting.api.v1.IPUsageRequest.to:type_name -> google.protobuf.Timestamp
	6,  // 6: metalstack.io.accounting.api.v1.IPUsageResponse.from:type_name -> google.protobuf.Timestamp
	6,  // 7: metalstack.io.accounting.api.v1.IPUsageResponse.to:type_name -> google.protobuf.Timestamp
	4,  // 8: metalstack.io.accounting.api.v1.IPUsageResponse.usage:type_name -> metalstack.io.accounting.api.v1.IPUsage
	5,  // 9: metalstack.io.accounting.api.v1.IPUsageResponse.accumulated_usage:type_name -> metalstack.io.accounting.api.v1.IPUsageAccumuluated
	6,  // 10: metalstack.io.accounting.api.v1.IPUsage.ip_start:type_name -> google.protobuf.Timestamp
	6,  // 11: metalstack.io.accounting.api.v1.IPUsage.ip_end:type_name -> google.protobuf.Timestamp
	7,  // 12: metalstack.io.accounting.api.v1.IPUsage.lifetime:type_name -> google.protobuf.Duration
	7,  // 13: metalstack.io.accounting.api.v1.IPUsageAccumuluated.lifetime:type_name -> google.protobuf.Duration
	1,  // 14: metalstack.io.accounting.api.v1.IPService.Added:input_type -> metalstack.io.accounting.api.v1.IPReport
	1,  // 15: metalstack.io.accounting.api.v1.IPService.Modified:input_type -> metalstack.io.accounting.api.v1.IPReport
	1,  // 16: metalstack.io.accounting.api.v1.IPService.Deleted:input_type -> metalstack.io.accounting.api.v1.IPReport
	2,  // 17: metalstack.io.accounting.api.v1.IPService.Usage:input_type -> metalstack.io.accounting.api.v1.IPUsageRequest
	8,  // 18: metalstack.io.accounting.api.v1.IPService.Added:output_type -> metalstack.io.accounting.api.v1.Empty
	8,  // 19: metalstack.io.accounting.api.v1.IPService.Modified:output_type -> metalstack.io.accounting.api.v1.Empty
	8,  // 20: metalstack.io.accounting.api.v1.IPService.Deleted:output_type -> metalstack.io.accounting.api.v1.Empty
	3,  // 21: metalstack.io.accounting.api.v1.IPService.Usage:output_type -> metalstack.io.accounting.api.v1.IPUsageResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_metalstack_io_accounting_api_v1_ip_proto_init() }
func file_metalstack_io_accounting_api_v1_ip_proto_init() {
	if File_metalstack_io_accounting_api_v1_ip_proto != nil {
		return
	}
	file_metalstack_io_accounting_api_v1_common_proto_init()
	file_metalstack_io_accounting_api_v1_ip_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_ip_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_ip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metalstack_io_accounting_api_v1_ip_proto_goTypes,
		DependencyIndexes: file_metalstack_io_accounting_api_v1_ip_proto_depIdxs,
		MessageInfos:      file_metalstack_io_accounting_api_v1_ip_proto_msgTypes,
	}.Build()
	File_metalstack_io_accounting_api_v1_ip_proto = out.File
	file_metalstack_io_accounting_api_v1_ip_proto_goTypes = nil
	file_metalstack_io_accounting_api_v1_ip_proto_depIdxs = nil
}
