// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: metalstack/io/accounting/api/v1/machine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Report         *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Start          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Machineid      string                 `protobuf:"bytes,4,opt,name=machineid,proto3" json:"machineid,omitempty"`
	Machinename    string                 `protobuf:"bytes,5,opt,name=machinename,proto3" json:"machinename,omitempty"`
	Sizeid         string                 `protobuf:"bytes,6,opt,name=sizeid,proto3" json:"sizeid,omitempty"`
	Imageid        string                 `protobuf:"bytes,7,opt,name=imageid,proto3" json:"imageid,omitempty"`
	Allocationuuid string                 `protobuf:"bytes,8,opt,name=allocationuuid,proto3" json:"allocationuuid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineReport) Reset() {
	*x = MachineReport{}
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineReport) ProtoMessage() {}

func (x *MachineReport) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineReport.ProtoReflect.Descriptor instead.
func (*MachineReport) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineReport) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *MachineReport) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *MachineReport) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *MachineReport) GetMachineid() string {
	if x != nil {
		return x.Machineid
	}
	return ""
}

func (x *MachineReport) GetMachinename() string {
	if x != nil {
		return x.Machinename
	}
	return ""
}

func (x *MachineReport) GetSizeid() string {
	if x != nil {
		return x.Sizeid
	}
	return ""
}

func (x *MachineReport) GetImageid() string {
	if x != nil {
		return x.Imageid
	}
	return ""
}

func (x *MachineReport) GetAllocationuuid() string {
	if x != nil {
		return x.Allocationuuid
	}
	return ""
}

type MachineUsageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          *UsageQuery            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Sizeid         *string                `protobuf:"bytes,2,opt,name=sizeid,proto3,oneof" json:"sizeid,omitempty"`
	Machineid      *string                `protobuf:"bytes,3,opt,name=machineid,proto3,oneof" json:"machineid,omitempty"`
	Partition      *string                `protobuf:"bytes,4,opt,name=partition,proto3,oneof" json:"partition,omitempty"`
	Allocationuuid *string                `protobuf:"bytes,5,opt,name=allocationuuid,proto3,oneof" json:"allocationuuid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineUsageRequest) Reset() {
	*x = MachineUsageRequest{}
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineUsageRequest) ProtoMessage() {}

func (x *MachineUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineUsageRequest.ProtoReflect.Descriptor instead.
func (*MachineUsageRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_machine_proto_rawDescGZIP(), []int{1}
}

func (x *MachineUsageRequest) GetQuery() *UsageQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *MachineUsageRequest) GetSizeid() string {
	if x != nil && x.Sizeid != nil {
		return *x.Sizeid
	}
	return ""
}

func (x *MachineUsageRequest) GetMachineid() string {
	if x != nil && x.Machineid != nil {
		return *x.Machineid
	}
	return ""
}

func (x *MachineUsageRequest) GetPartition() string {
	if x != nil && x.Partition != nil {
		return *x.Partition
	}
	return ""
}

func (x *MachineUsageRequest) GetAllocationuuid() string {
	if x != nil && x.Allocationuuid != nil {
		return *x.Allocationuuid
	}
	return ""
}

type MachineUsageResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	From             *timestamppb.Timestamp    `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp    `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Usage            []*MachineUsage           `protobuf:"bytes,3,rep,name=usage,proto3" json:"usage,omitempty"`
	AccumulatedUsage *MachineUsageAccumuluated `protobuf:"bytes,4,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MachineUsageResponse) Reset() {
	*x = MachineUsageResponse{}
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineUsageResponse) ProtoMessage() {}

func (x *MachineUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineUsageResponse.ProtoReflect.Descriptor instead.
func (*MachineUsageResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineUsageResponse) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MachineUsageResponse) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MachineUsageResponse) GetUsage() []*MachineUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *MachineUsageResponse) GetAccumulatedUsage() *MachineUsageAccumuluated {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

type MachineUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Partition      string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Tenant         string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Projectid      string                 `protobuf:"bytes,3,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Machineid      string                 `protobuf:"bytes,4,opt,name=machineid,proto3" json:"machineid,omitempty"`
	Machinename    string                 `protobuf:"bytes,5,opt,name=machinename,proto3" json:"machinename,omitempty"`
	Sizeid         string                 `protobuf:"bytes,6,opt,name=sizeid,proto3" json:"sizeid,omitempty"`
	Imageid        string                 `protobuf:"bytes,7,opt,name=imageid,proto3" json:"imageid,omitempty"`
	Clusterid      string                 `protobuf:"bytes,8,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	Clustername    string                 `protobuf:"bytes,9,opt,name=clustername,proto3" json:"clustername,omitempty"`
	Start          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=start,proto3" json:"start,omitempty"`
	End            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=end,proto3" json:"end,omitempty"`
	Lifetime       *durationpb.Duration   `protobuf:"bytes,12,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	Projectname    string                 `protobuf:"bytes,13,opt,name=projectname,proto3" json:"projectname,omitempty"`
	Tenantname     string                 `protobuf:"bytes,14,opt,name=tenantname,proto3" json:"tenantname,omitempty"`
	Contractnumber string                 `protobuf:"bytes,15,opt,name=contractnumber,proto3" json:"contractnumber,omitempty"`
	Debtorid       string                 `protobuf:"bytes,16,opt,name=debtorid,proto3" json:"debtorid,omitempty"`
	Allocationuuid string                 `protobuf:"bytes,17,opt,name=allocationuuid,proto3" json:"allocationuuid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineUsage) Reset() {
	*x = MachineUsage{}
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineUsage) ProtoMessage() {}

func (x *MachineUsage) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineUsage.ProtoReflect.Descriptor instead.
func (*MachineUsage) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_machine_proto_rawDescGZIP(), []int{3}
}

func (x *MachineUsage) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *MachineUsage) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *MachineUsage) GetProjectid() string {
	if x != nil {
		return x.Projectid
	}
	return ""
}

func (x *MachineUsage) GetMachineid() string {
	if x != nil {
		return x.Machineid
	}
	return ""
}

func (x *MachineUsage) GetMachinename() string {
	if x != nil {
		return x.Machinename
	}
	return ""
}

func (x *MachineUsage) GetSizeid() string {
	if x != nil {
		return x.Sizeid
	}
	return ""
}

func (x *MachineUsage) GetImageid() string {
	if x != nil {
		return x.Imageid
	}
	return ""
}

func (x *MachineUsage) GetClusterid() string {
	if x != nil {
		return x.Clusterid
	}
	return ""
}

func (x *MachineUsage) GetClustername() string {
	if x != nil {
		return x.Clustername
	}
	return ""
}

func (x *MachineUsage) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *MachineUsage) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *MachineUsage) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *MachineUsage) GetProjectname() string {
	if x != nil {
		return x.Projectname
	}
	return ""
}

func (x *MachineUsage) GetTenantname() string {
	if x != nil {
		return x.Tenantname
	}
	return ""
}

func (x *MachineUsage) GetContractnumber() string {
	if x != nil {
		return x.Contractnumber
	}
	return ""
}

func (x *MachineUsage) GetDebtorid() string {
	if x != nil {
		return x.Debtorid
	}
	return ""
}

func (x *MachineUsage) GetAllocationuuid() string {
	if x != nil {
		return x.Allocationuuid
	}
	return ""
}

type MachineUsageAccumuluated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineUsageAccumuluated) Reset() {
	*x = MachineUsageAccumuluated{}
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineUsageAccumuluated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineUsageAccumuluated) ProtoMessage() {}

func (x *MachineUsageAccumuluated) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineUsageAccumuluated.ProtoReflect.Descriptor instead.
func (*MachineUsageAccumuluated) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_machine_proto_rawDescGZIP(), []int{4}
}

func (x *MachineUsageAccumuluated) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

var File_metalstack_io_accounting_api_v1_machine_proto protoreflect.FileDescriptor

const file_metalstack_io_accounting_api_v1_machine_proto_rawDesc = "" +
	"\n" +
	"-metalstack/io/accounting/api/v1/machine.proto\x12\x1fmetalstack.io.accounting.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,metalstack/io/accounting/api/v1/common.proto\"\xca\x02\n" +
	"\rMachineReport\x12?\n" +
	"\x06report\x18\x01 \x01(\v2'.metalstack.io.accounting.api.v1.ReportR\x06report\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1c\n" +
	"\tmachineid\x18\x04 \x01(\tR\tmachineid\x12 \n" +
	"\vmachinename\x18\x05 \x01(\tR\vmachinename\x12\x16\n" +
	"\x06sizeid\x18\x06 \x01(\tR\x06sizeid\x12\x18\n" +
	"\aimageid\x18\a \x01(\tR\aimageid\x12&\n" +
	"\x0eallocationuuid\x18\b \x01(\tR\x0eallocationuuid\"\xa2\x02\n" +
	"\x13MachineUsageRequest\x12A\n" +
	"\x05query\x18\x01 \x01(\v2+.metalstack.io.accounting.api.v1.UsageQueryR\x05query\x12\x1b\n" +
	"\x06sizeid\x18\x02 \x01(\tH\x00R\x06sizeid\x88\x01\x01\x12!\n" +
	"\tmachineid\x18\x03 \x01(\tH\x01R\tmachineid\x88\x01\x01\x12!\n" +
	"\tpartition\x18\x04 \x01(\tH\x02R\tpartition\x88\x01\x01\x12+\n" +
	"\x0eallocationuuid\x18\x05 \x01(\tH\x03R\x0eallocationuuid\x88\x01\x01B\t\n" +
	"\a_sizeidB\f\n" +
	"\n" +
	"_machineidB\f\n" +
	"\n" +
	"_partitionB\x11\n" +
	"\x0f_allocationuuid\"\x9f\x02\n" +
	"\x14MachineUsageResponse\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12C\n" +
	"\x05usage\x18\x03 \x03(\v2-.metalstack.io.accounting.api.v1.MachineUsageR\x05usage\x12f\n" +
	"\x11accumulated_usage\x18\x04 \x01(\v29.metalstack.io.accounting.api.v1.MachineUsageAccumuluatedR\x10accumulatedUsage\"\xd9\x04\n" +
	"\fMachineUsage\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tprojectid\x18\x03 \x01(\tR\tprojectid\x12\x1c\n" +
	"\tmachineid\x18\x04 \x01(\tR\tmachineid\x12 \n" +
	"\vmachinename\x18\x05 \x01(\tR\vmachinename\x12\x16\n" +
	"\x06sizeid\x18\x06 \x01(\tR\x06sizeid\x12\x18\n" +
	"\aimageid\x18\a \x01(\tR\aimageid\x12\x1c\n" +
	"\tclusterid\x18\b \x01(\tR\tclusterid\x12 \n" +
	"\vclustername\x18\t \x01(\tR\vclustername\x120\n" +
	"\x05start\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x125\n" +
	"\blifetime\x18\f \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12 \n" +
	"\vprojectname\x18\r \x01(\tR\vprojectname\x12\x1e\n" +
	"\n" +
	"tenantname\x18\x0e \x01(\tR\n" +
	"tenantname\x12&\n" +
	"\x0econtractnumber\x18\x0f \x01(\tR\x0econtractnumber\x12\x1a\n" +
	"\bdebtorid\x18\x10 \x01(\tR\bdebtorid\x12&\n" +
	"\x0eallocationuuid\x18\x11 \x01(\tR\x0eallocationuuid\"Q\n" +
	"\x18MachineUsageAccumuluated\x125\n" +
	"\blifetime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\blifetime2\xae\x03\n" +
	"\x0eMachineService\x12_\n" +
	"\x05Added\x12..metalstack.io.accounting.api.v1.MachineReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12b\n" +
	"\bModified\x12..metalstack.io.accounting.api.v1.MachineReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12a\n" +
	"\aDeleted\x12..metalstack.io.accounting.api.v1.MachineReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12t\n" +
	"\x05Usage\x124.metalstack.io.accounting.api.v1.MachineUsageRequest\x1a5.metalstack.io.accounting.api.v1.MachineUsageResponseB\rZ\vpkg/apis/v1b\x06proto3"

var (
	file_metalstack_io_accounting_api_v1_machine_proto_rawDescOnce sync.Once
	file_metalstack_io_accounting_api_v1_machine_proto_rawDescData []byte
)

func file_metalstack_io_accounting_api_v1_machine_proto_rawDescGZIP() []byte {
	file_metalstack_io_accounting_api_v1_machine_proto_rawDescOnce.Do(func() {
		file_metalstack_io_accounting_api_v1_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_machine_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_machine_proto_rawDesc)))
	})
	return file_metalstack_io_accounting_api_v1_machine_proto_rawDescData
}

var file_metalstack_io_accounting_api_v1_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metalstack_io_accounting_api_v1_machine_proto_goTypes = []any{
	(*MachineReport)(nil),            // 0: metalstack.io.accounting.api.v1.MachineReport
	(*MachineUsageRequest)(nil),      // 1: metalstack.io.accounting.api.v1.MachineUsageRequest
	(*MachineUsageResponse)(nil),     // 2: metalstack.io.accounting.api.v1.MachineUsageResponse
	(*MachineUsage)(nil),             // 3: metalstack.io.accounting.api.v1.MachineUsage
	(*MachineUsageAccumuluated)(nil), // 4: metalstack.io.accounting.api.v1.MachineUsageAccumuluated
	(*Report)(nil),                   // 5: metalstack.io.accounting.api.v1.Report
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
	(*UsageQuery)(nil),               // 7: metalstack.io.accounting.api.v1.UsageQuery
	(*durationpb.Duration)(nil),      // 8: google.protobuf.Duration
	(*Empty)(nil),                    // 9: metalstack.io.accounting.api.v1.Empty
}
var file_metalstack_io_accounting_api_v1_machine_proto_depIdxs = []int32{
	5,  // 0: metalstack.io.accounting.api.v1.MachineReport.report:type_name -> metalstack.io.accounting.api.v1.Report
	6,  // 1: metalstack.io.accounting.api.v1.MachineReport.start:type_name -> google.protobuf.Timestamp
	6,  // 2: metalstack.io.accounting.api.v1.MachineReport.end:type_name -> google.protobuf.Timestamp
	7,  // 3: metalstack.io.accounting.api.v1.MachineUsageRequest.query:type_name -> metalstack.io.accounting.api.v1.UsageQuery
	6,  // 4: metalstack.io.accounting.api.v1.MachineUsageResponse.from:type_name -> google.protobuf.Timestamp
	6,  // 5: metalstack.io.accounting.api.v1.MachineUsageResponse.to:type_name -> google.protobuf.Timestamp
	3,  // 6: metalstack.io.accounting.api.v1.MachineUsageResponse.usage:type_name -> metalstack.io.accounting.api.v1.MachineUsage
	4,  // 7: metalstack.io.accounting.api.v1.MachineUsageResponse.accumulated_usage:type_name -> metalstack.io.accounting.api.v1.MachineUsageAccumuluated
	6,  // 8: metalstack.io.accounting.api.v1.MachineUsage.start:type_name -> google.protobuf.Timestamp
	6,  // 9: metalstack.io.accounting.api.v1.MachineUsage.end:type_name -> google.protobuf.Timestamp
	8,  // 10: metalstack.io.accounting.api.v1.MachineUsage.lifetime:type_name -> google.protobuf.Duration
	8,  // 11: metalstack.io.accounting.api.v1.MachineUsageAccumuluated.lifetime:type_name -> google.protobuf.Duration
	0,  // 12: metalstack.io.accounting.api.v1.MachineService.Added:input_type -> metalstack.io.accounting.api.v1.MachineReport
	0,  // 13: metalstack.io.accounting.api.v1.MachineService.Modified:input_type -> metalstack.io.accounting.api.v1.MachineReport
	0,  // 14: metalstack.io.accounting.api.v1.MachineService.Deleted:input_type -> metalstack.io.accounting.api.v1.MachineReport
	1,  // 15: metalstack.io.accounting.api.v1.MachineService.Usage:input_type -> metalstack.io.accounting.api.v1.MachineUsageRequest
	9,  // 16: metalstack.io.accounting.api.v1.MachineService.Added:output_type -> metalstack.io.accounting.api.v1.Empty
	9,  // 17: metalstack.io.accounting.api.v1.MachineService.Modified:output_type -> metalstack.io.accounting.api.v1.Empty
	9,  // 18: metalstack.io.accounting.api.v1.MachineService.Deleted:output_type -> metalstack.io.accounting.api.v1.Empty
	2,  // 19: metalstack.io.accounting.api.v1.MachineService.Usage:output_type -> metalstack.io.accounting.api.v1.MachineUsageResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_metalstack_io_accounting_api_v1_machine_proto_init() }
func file_metalstack_io_accounting_api_v1_machine_proto_init() {
	if File_metalstack_io_accounting_api_v1_machine_proto != nil {
		return
	}
	file_metalstack_io_accounting_api_v1_common_proto_init()
	file_metalstack_io_accounting_api_v1_machine_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_machine_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metalstack_io_accounting_api_v1_machine_proto_goTypes,
		DependencyIndexes: file_metalstack_io_accounting_api_v1_machine_proto_depIdxs,
		MessageInfos:      file_metalstack_io_accounting_api_v1_machine_proto_msgTypes,
	}.Build()
	File_metalstack_io_accounting_api_v1_machine_proto = out.File
	file_metalstack_io_accounting_api_v1_machine_proto_goTypes = nil
	file_metalstack_io_accounting_api_v1_machine_proto_depIdxs = nil
}
