// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: metalstack/io/accounting/api/v1/network_traffic.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkTraffic struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Device string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	In     uint64                 `protobuf:"varint,2,opt,name=in,proto3" json:"in,omitempty"`
	Out    uint64                 `protobuf:"varint,3,opt,name=out,proto3" json:"out,omitempty"`
	// Deprecated: Marked as deprecated in metalstack/io/accounting/api/v1/network_traffic.proto.
	Total         uint64 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkTraffic) Reset() {
	*x = NetworkTraffic{}
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTraffic) ProtoMessage() {}

func (x *NetworkTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTraffic.ProtoReflect.Descriptor instead.
func (*NetworkTraffic) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkTraffic) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NetworkTraffic) GetIn() uint64 {
	if x != nil {
		return x.In
	}
	return 0
}

func (x *NetworkTraffic) GetOut() uint64 {
	if x != nil {
		return x.Out
	}
	return 0
}

// Deprecated: Marked as deprecated in metalstack/io/accounting/api/v1/network_traffic.proto.
func (x *NetworkTraffic) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type NetworkTrafficReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Report         *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	TrafficReports []*NetworkTraffic      `protobuf:"bytes,2,rep,name=traffic_reports,json=trafficReports,proto3" json:"traffic_reports,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkTrafficReport) Reset() {
	*x = NetworkTrafficReport{}
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTrafficReport) ProtoMessage() {}

func (x *NetworkTrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTrafficReport.ProtoReflect.Descriptor instead.
func (*NetworkTrafficReport) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkTrafficReport) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *NetworkTrafficReport) GetTrafficReports() []*NetworkTraffic {
	if x != nil {
		return x.TrafficReports
	}
	return nil
}

type NetworkUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *UsageQuery            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Device        *string                `protobuf:"bytes,2,opt,name=device,proto3,oneof" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkUsageRequest) Reset() {
	*x = NetworkUsageRequest{}
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUsageRequest) ProtoMessage() {}

func (x *NetworkUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUsageRequest.ProtoReflect.Descriptor instead.
func (*NetworkUsageRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkUsageRequest) GetQuery() *UsageQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *NetworkUsageRequest) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

type NetworkUsageResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	From             *timestamppb.Timestamp    `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp    `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Usage            []*NetworkUsage           `protobuf:"bytes,3,rep,name=usage,proto3" json:"usage,omitempty"`
	AccumulatedUsage *NetworkUsageAccumuluated `protobuf:"bytes,4,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkUsageResponse) Reset() {
	*x = NetworkUsageResponse{}
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUsageResponse) ProtoMessage() {}

func (x *NetworkUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUsageResponse.ProtoReflect.Descriptor instead.
func (*NetworkUsageResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkUsageResponse) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *NetworkUsageResponse) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *NetworkUsageResponse) GetUsage() []*NetworkUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *NetworkUsageResponse) GetAccumulatedUsage() *NetworkUsageAccumuluated {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

type NetworkUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Partition      string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Tenant         string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Projectid      string                 `protobuf:"bytes,3,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Clusterid      string                 `protobuf:"bytes,4,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	Clustername    string                 `protobuf:"bytes,5,opt,name=clustername,proto3" json:"clustername,omitempty"`
	Device         string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	InBytes        string                 `protobuf:"bytes,7,opt,name=in_bytes,json=inBytes,proto3" json:"in_bytes,omitempty"`
	OutBytes       string                 `protobuf:"bytes,8,opt,name=out_bytes,json=outBytes,proto3" json:"out_bytes,omitempty"`
	Lifetime       *durationpb.Duration   `protobuf:"bytes,11,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	Warnings       []string               `protobuf:"bytes,12,rep,name=warnings,proto3" json:"warnings,omitempty"`
	TotalBytes     string                 `protobuf:"bytes,13,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Projectname    string                 `protobuf:"bytes,14,opt,name=projectname,proto3" json:"projectname,omitempty"`
	Annotations    []string               `protobuf:"bytes,15,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Tenantname     string                 `protobuf:"bytes,16,opt,name=tenantname,proto3" json:"tenantname,omitempty"`
	Contractnumber string                 `protobuf:"bytes,17,opt,name=contractnumber,proto3" json:"contractnumber,omitempty"`
	Debtorid       string                 `protobuf:"bytes,18,opt,name=debtorid,proto3" json:"debtorid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkUsage) Reset() {
	*x = NetworkUsage{}
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUsage) ProtoMessage() {}

func (x *NetworkUsage) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUsage.ProtoReflect.Descriptor instead.
func (*NetworkUsage) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkUsage) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *NetworkUsage) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *NetworkUsage) GetProjectid() string {
	if x != nil {
		return x.Projectid
	}
	return ""
}

func (x *NetworkUsage) GetClusterid() string {
	if x != nil {
		return x.Clusterid
	}
	return ""
}

func (x *NetworkUsage) GetClustername() string {
	if x != nil {
		return x.Clustername
	}
	return ""
}

func (x *NetworkUsage) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NetworkUsage) GetInBytes() string {
	if x != nil {
		return x.InBytes
	}
	return ""
}

func (x *NetworkUsage) GetOutBytes() string {
	if x != nil {
		return x.OutBytes
	}
	return ""
}

func (x *NetworkUsage) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *NetworkUsage) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *NetworkUsage) GetTotalBytes() string {
	if x != nil {
		return x.TotalBytes
	}
	return ""
}

func (x *NetworkUsage) GetProjectname() string {
	if x != nil {
		return x.Projectname
	}
	return ""
}

func (x *NetworkUsage) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *NetworkUsage) GetTenantname() string {
	if x != nil {
		return x.Tenantname
	}
	return ""
}

func (x *NetworkUsage) GetContractnumber() string {
	if x != nil {
		return x.Contractnumber
	}
	return ""
}

func (x *NetworkUsage) GetDebtorid() string {
	if x != nil {
		return x.Debtorid
	}
	return ""
}

type NetworkUsageAccumuluated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	InBytes       string                 `protobuf:"bytes,2,opt,name=in_bytes,json=inBytes,proto3" json:"in_bytes,omitempty"`
	OutBytes      string                 `protobuf:"bytes,3,opt,name=out_bytes,json=outBytes,proto3" json:"out_bytes,omitempty"`
	TotalBytes    string                 `protobuf:"bytes,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkUsageAccumuluated) Reset() {
	*x = NetworkUsageAccumuluated{}
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkUsageAccumuluated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUsageAccumuluated) ProtoMessage() {}

func (x *NetworkUsageAccumuluated) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUsageAccumuluated.ProtoReflect.Descriptor instead.
func (*NetworkUsageAccumuluated) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkUsageAccumuluated) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *NetworkUsageAccumuluated) GetInBytes() string {
	if x != nil {
		return x.InBytes
	}
	return ""
}

func (x *NetworkUsageAccumuluated) GetOutBytes() string {
	if x != nil {
		return x.OutBytes
	}
	return ""
}

func (x *NetworkUsageAccumuluated) GetTotalBytes() string {
	if x != nil {
		return x.TotalBytes
	}
	return ""
}

var File_metalstack_io_accounting_api_v1_network_traffic_proto protoreflect.FileDescriptor

const file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDesc = "" +
	"\n" +
	"5metalstack/io/accounting/api/v1/network_traffic.proto\x12\x1fmetalstack.io.accounting.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,metalstack/io/accounting/api/v1/common.proto\"d\n" +
	"\x0eNetworkTraffic\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x0e\n" +
	"\x02in\x18\x02 \x01(\x04R\x02in\x12\x10\n" +
	"\x03out\x18\x03 \x01(\x04R\x03out\x12\x18\n" +
	"\x05total\x18\x04 \x01(\x04B\x02\x18\x01R\x05total\"\xb1\x01\n" +
	"\x14NetworkTrafficReport\x12?\n" +
	"\x06report\x18\x01 \x01(\v2'.metalstack.io.accounting.api.v1.ReportR\x06report\x12X\n" +
	"\x0ftraffic_reports\x18\x02 \x03(\v2/.metalstack.io.accounting.api.v1.NetworkTrafficR\x0etrafficReports\"\x80\x01\n" +
	"\x13NetworkUsageRequest\x12A\n" +
	"\x05query\x18\x01 \x01(\v2+.metalstack.io.accounting.api.v1.UsageQueryR\x05query\x12\x1b\n" +
	"\x06device\x18\x02 \x01(\tH\x00R\x06device\x88\x01\x01B\t\n" +
	"\a_device\"\x9f\x02\n" +
	"\x14NetworkUsageResponse\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12C\n" +
	"\x05usage\x18\x03 \x03(\v2-.metalstack.io.accounting.api.v1.NetworkUsageR\x05usage\x12f\n" +
	"\x11accumulated_usage\x18\x04 \x01(\v29.metalstack.io.accounting.api.v1.NetworkUsageAccumuluatedR\x10accumulatedUsage\"\x8e\x04\n" +
	"\fNetworkUsage\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tprojectid\x18\x03 \x01(\tR\tprojectid\x12\x1c\n" +
	"\tclusterid\x18\x04 \x01(\tR\tclusterid\x12 \n" +
	"\vclustername\x18\x05 \x01(\tR\vclustername\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x19\n" +
	"\bin_bytes\x18\a \x01(\tR\ainBytes\x12\x1b\n" +
	"\tout_bytes\x18\b \x01(\tR\boutBytes\x125\n" +
	"\blifetime\x18\v \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1a\n" +
	"\bwarnings\x18\f \x03(\tR\bwarnings\x12\x1f\n" +
	"\vtotal_bytes\x18\r \x01(\tR\n" +
	"totalBytes\x12 \n" +
	"\vprojectname\x18\x0e \x01(\tR\vprojectname\x12 \n" +
	"\vannotations\x18\x0f \x03(\tR\vannotations\x12\x1e\n" +
	"\n" +
	"tenantname\x18\x10 \x01(\tR\n" +
	"tenantname\x12&\n" +
	"\x0econtractnumber\x18\x11 \x01(\tR\x0econtractnumber\x12\x1a\n" +
	"\bdebtorid\x18\x12 \x01(\tR\bdebtorid\"\xaa\x01\n" +
	"\x18NetworkUsageAccumuluated\x125\n" +
	"\blifetime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x19\n" +
	"\bin_bytes\x18\x02 \x01(\tR\ainBytes\x12\x1b\n" +
	"\tout_bytes\x18\x03 \x01(\tR\boutBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\tR\n" +
	"totalBytes2\xf8\x01\n" +
	"\x15NetworkTrafficService\x12i\n" +
	"\bModified\x125.metalstack.io.accounting.api.v1.NetworkTrafficReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12t\n" +
	"\x05Usage\x124.metalstack.io.accounting.api.v1.NetworkUsageRequest\x1a5.metalstack.io.accounting.api.v1.NetworkUsageResponseB\rZ\vpkg/apis/v1b\x06proto3"

var (
	file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescOnce sync.Once
	file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescData []byte
)

func file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescGZIP() []byte {
	file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescOnce.Do(func() {
		file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDesc)))
	})
	return file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDescData
}

var file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metalstack_io_accounting_api_v1_network_traffic_proto_goTypes = []any{
	(*NetworkTraffic)(nil),           // 0: metalstack.io.accounting.api.v1.NetworkTraffic
	(*NetworkTrafficReport)(nil),     // 1: metalstack.io.accounting.api.v1.NetworkTrafficReport
	(*NetworkUsageRequest)(nil),      // 2: metalstack.io.accounting.api.v1.NetworkUsageRequest
	(*NetworkUsageResponse)(nil),     // 3: metalstack.io.accounting.api.v1.NetworkUsageResponse
	(*NetworkUsage)(nil),             // 4: metalstack.io.accounting.api.v1.NetworkUsage
	(*NetworkUsageAccumuluated)(nil), // 5: metalstack.io.accounting.api.v1.NetworkUsageAccumuluated
	(*Report)(nil),                   // 6: metalstack.io.accounting.api.v1.Report
	(*UsageQuery)(nil),               // 7: metalstack.io.accounting.api.v1.UsageQuery
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 9: google.protobuf.Duration
	(*Empty)(nil),                    // 10: metalstack.io.accounting.api.v1.Empty
}
var file_metalstack_io_accounting_api_v1_network_traffic_proto_depIdxs = []int32{
	6,  // 0: metalstack.io.accounting.api.v1.NetworkTrafficReport.report:type_name -> metalstack.io.accounting.api.v1.Report
	0,  // 1: metalstack.io.accounting.api.v1.NetworkTrafficReport.traffic_reports:type_name -> metalstack.io.accounting.api.v1.NetworkTraffic
	7,  // 2: metalstack.io.accounting.api.v1.NetworkUsageRequest.query:type_name -> metalstack.io.accounting.api.v1.UsageQuery
	8,  // 3: metalstack.io.accounting.api.v1.NetworkUsageResponse.from:type_name -> google.protobuf.Timestamp
	8,  // 4: metalstack.io.accounting.api.v1.NetworkUsageResponse.to:type_name -> google.protobuf.Timestamp
	4,  // 5: metalstack.io.accounting.api.v1.NetworkUsageResponse.usage:type_name -> metalstack.io.accounting.api.v1.NetworkUsage
	5,  // 6: metalstack.io.accounting.api.v1.NetworkUsageResponse.accumulated_usage:type_name -> metalstack.io.accounting.api.v1.NetworkUsageAccumuluated
	9,  // 7: metalstack.io.accounting.api.v1.NetworkUsage.lifetime:type_name -> google.protobuf.Duration
	9,  // 8: metalstack.io.accounting.api.v1.NetworkUsageAccumuluated.lifetime:type_name -> google.protobuf.Duration
	1,  // 9: metalstack.io.accounting.api.v1.NetworkTrafficService.Modified:input_type -> metalstack.io.accounting.api.v1.NetworkTrafficReport
	2,  // 10: metalstack.io.accounting.api.v1.NetworkTrafficService.Usage:input_type -> metalstack.io.accounting.api.v1.NetworkUsageRequest
	10, // 11: metalstack.io.accounting.api.v1.NetworkTrafficService.Modified:output_type -> metalstack.io.accounting.api.v1.Empty
	3,  // 12: metalstack.io.accounting.api.v1.NetworkTrafficService.Usage:output_type -> metalstack.io.accounting.api.v1.NetworkUsageResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_metalstack_io_accounting_api_v1_network_traffic_proto_init() }
func file_metalstack_io_accounting_api_v1_network_traffic_proto_init() {
	if File_metalstack_io_accounting_api_v1_network_traffic_proto != nil {
		return
	}
	file_metalstack_io_accounting_api_v1_common_proto_init()
	file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_network_traffic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metalstack_io_accounting_api_v1_network_traffic_proto_goTypes,
		DependencyIndexes: file_metalstack_io_accounting_api_v1_network_traffic_proto_depIdxs,
		MessageInfos:      file_metalstack_io_accounting_api_v1_network_traffic_proto_msgTypes,
	}.Build()
	File_metalstack_io_accounting_api_v1_network_traffic_proto = out.File
	file_metalstack_io_accounting_api_v1_network_traffic_proto_goTypes = nil
	file_metalstack_io_accounting_api_v1_network_traffic_proto_depIdxs = nil
}
