// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: metalstack/io/accounting/api/v1/pod.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUuid       string                 `protobuf:"bytes,2,opt,name=pod_uuid,json=podUuid,proto3" json:"pod_uuid,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Cpus          string                 `protobuf:"bytes,5,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory        string                 `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_pod_proto_rawDescGZIP(), []int{0}
}

func (x *Container) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Container) GetPodUuid() string {
	if x != nil {
		return x.PodUuid
	}
	return ""
}

func (x *Container) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetCpus() string {
	if x != nil {
		return x.Cpus
	}
	return ""
}

func (x *Container) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type PodReport struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	KubernetesReport *KubernetesResourceReport `protobuf:"bytes,1,opt,name=kubernetes_report,json=kubernetesReport,proto3" json:"kubernetes_report,omitempty"`
	Containers       []*Container              `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	Annotations      []string                  `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PodReport) Reset() {
	*x = PodReport{}
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodReport) ProtoMessage() {}

func (x *PodReport) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodReport.ProtoReflect.Descriptor instead.
func (*PodReport) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_pod_proto_rawDescGZIP(), []int{1}
}

func (x *PodReport) GetKubernetesReport() *KubernetesResourceReport {
	if x != nil {
		return x.KubernetesReport
	}
	return nil
}

func (x *PodReport) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *PodReport) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ContainerUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *UsageQuery            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Annotations   []string               `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerUsageRequest) Reset() {
	*x = ContainerUsageRequest{}
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerUsageRequest) ProtoMessage() {}

func (x *ContainerUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerUsageRequest.ProtoReflect.Descriptor instead.
func (*ContainerUsageRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_pod_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerUsageRequest) GetQuery() *UsageQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ContainerUsageRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ContainerUsageRequest) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ContainerUsageResponse struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	From             *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Usage            []*ContainerUsage           `protobuf:"bytes,3,rep,name=usage,proto3" json:"usage,omitempty"`
	AccumulatedUsage *ContainerUsageAccumuluated `protobuf:"bytes,4,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerUsageResponse) Reset() {
	*x = ContainerUsageResponse{}
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerUsageResponse) ProtoMessage() {}

func (x *ContainerUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerUsageResponse.ProtoReflect.Descriptor instead.
func (*ContainerUsageResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_pod_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerUsageResponse) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ContainerUsageResponse) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ContainerUsageResponse) GetUsage() []*ContainerUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ContainerUsageResponse) GetAccumulatedUsage() *ContainerUsageAccumuluated {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

type ContainerUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Partition      string                 `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Tenant         string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Projectid      string                 `protobuf:"bytes,3,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Clusterid      string                 `protobuf:"bytes,4,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	Clustername    string                 `protobuf:"bytes,5,opt,name=clustername,proto3" json:"clustername,omitempty"`
	Namespace      string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodUuid        string                 `protobuf:"bytes,7,opt,name=pod_uuid,json=podUuid,proto3" json:"pod_uuid,omitempty"`
	PodName        string                 `protobuf:"bytes,8,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodStart       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=pod_start,json=podStart,proto3" json:"pod_start,omitempty"`
	PodEnd         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=pod_end,json=podEnd,proto3" json:"pod_end,omitempty"`
	ContainerName  string                 `protobuf:"bytes,11,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Lifetime       *durationpb.Duration   `protobuf:"bytes,12,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	CpuSeconds     string                 `protobuf:"bytes,13,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	MemorySeconds  string                 `protobuf:"bytes,14,opt,name=memory_seconds,json=memorySeconds,proto3" json:"memory_seconds,omitempty"`
	Warnings       []string               `protobuf:"bytes,15,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ContainerImage string                 `protobuf:"bytes,16,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	Annotations    []string               `protobuf:"bytes,17,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Projectname    string                 `protobuf:"bytes,18,opt,name=projectname,proto3" json:"projectname,omitempty"`
	Tenantname     string                 `protobuf:"bytes,19,opt,name=tenantname,proto3" json:"tenantname,omitempty"`
	Contractnumber string                 `protobuf:"bytes,20,opt,name=contractnumber,proto3" json:"contractnumber,omitempty"`
	Debtorid       string                 `protobuf:"bytes,21,opt,name=debtorid,proto3" json:"debtorid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerUsage) Reset() {
	*x = ContainerUsage{}
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerUsage) ProtoMessage() {}

func (x *ContainerUsage) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerUsage.ProtoReflect.Descriptor instead.
func (*ContainerUsage) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_pod_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerUsage) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *ContainerUsage) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ContainerUsage) GetProjectid() string {
	if x != nil {
		return x.Projectid
	}
	return ""
}

func (x *ContainerUsage) GetClusterid() string {
	if x != nil {
		return x.Clusterid
	}
	return ""
}

func (x *ContainerUsage) GetClustername() string {
	if x != nil {
		return x.Clustername
	}
	return ""
}

func (x *ContainerUsage) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ContainerUsage) GetPodUuid() string {
	if x != nil {
		return x.PodUuid
	}
	return ""
}

func (x *ContainerUsage) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ContainerUsage) GetPodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PodStart
	}
	return nil
}

func (x *ContainerUsage) GetPodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PodEnd
	}
	return nil
}

func (x *ContainerUsage) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerUsage) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *ContainerUsage) GetCpuSeconds() string {
	if x != nil {
		return x.CpuSeconds
	}
	return ""
}

func (x *ContainerUsage) GetMemorySeconds() string {
	if x != nil {
		return x.MemorySeconds
	}
	return ""
}

func (x *ContainerUsage) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ContainerUsage) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *ContainerUsage) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ContainerUsage) GetProjectname() string {
	if x != nil {
		return x.Projectname
	}
	return ""
}

func (x *ContainerUsage) GetTenantname() string {
	if x != nil {
		return x.Tenantname
	}
	return ""
}

func (x *ContainerUsage) GetContractnumber() string {
	if x != nil {
		return x.Contractnumber
	}
	return ""
}

func (x *ContainerUsage) GetDebtorid() string {
	if x != nil {
		return x.Debtorid
	}
	return ""
}

type ContainerUsageAccumuluated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	CpuSeconds    string                 `protobuf:"bytes,2,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	MemorySeconds string                 `protobuf:"bytes,3,opt,name=memory_seconds,json=memorySeconds,proto3" json:"memory_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerUsageAccumuluated) Reset() {
	*x = ContainerUsageAccumuluated{}
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerUsageAccumuluated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerUsageAccumuluated) ProtoMessage() {}

func (x *ContainerUsageAccumuluated) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerUsageAccumuluated.ProtoReflect.Descriptor instead.
func (*ContainerUsageAccumuluated) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_pod_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerUsageAccumuluated) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *ContainerUsageAccumuluated) GetCpuSeconds() string {
	if x != nil {
		return x.CpuSeconds
	}
	return ""
}

func (x *ContainerUsageAccumuluated) GetMemorySeconds() string {
	if x != nil {
		return x.MemorySeconds
	}
	return ""
}

var File_metalstack_io_accounting_api_v1_pod_proto protoreflect.FileDescriptor

const file_metalstack_io_accounting_api_v1_pod_proto_rawDesc = "" +
	"\n" +
	")metalstack/io/accounting/api/v1/pod.proto\x12\x1fmetalstack.io.accounting.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,metalstack/io/accounting/api/v1/common.proto\"\xaa\x01\n" +
	"\tContainer\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x19\n" +
	"\bpod_uuid\x18\x02 \x01(\tR\apodUuid\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x12\n" +
	"\x04cpus\x18\x05 \x01(\tR\x04cpus\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\tR\x06memory\"\xe1\x01\n" +
	"\tPodReport\x12f\n" +
	"\x11kubernetes_report\x18\x01 \x01(\v29.metalstack.io.accounting.api.v1.KubernetesResourceReportR\x10kubernetesReport\x12J\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2*.metalstack.io.accounting.api.v1.ContainerR\n" +
	"containers\x12 \n" +
	"\vannotations\x18\x03 \x03(\tR\vannotations\"\xad\x01\n" +
	"\x15ContainerUsageRequest\x12A\n" +
	"\x05query\x18\x01 \x01(\v2+.metalstack.io.accounting.api.v1.UsageQueryR\x05query\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12 \n" +
	"\vannotations\x18\x03 \x03(\tR\vannotationsB\f\n" +
	"\n" +
	"_namespace\"\xa5\x02\n" +
	"\x16ContainerUsageResponse\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12E\n" +
	"\x05usage\x18\x03 \x03(\v2/.metalstack.io.accounting.api.v1.ContainerUsageR\x05usage\x12h\n" +
	"\x11accumulated_usage\x18\x04 \x01(\v2;.metalstack.io.accounting.api.v1.ContainerUsageAccumuluatedR\x10accumulatedUsage\"\xf9\x05\n" +
	"\x0eContainerUsage\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tprojectid\x18\x03 \x01(\tR\tprojectid\x12\x1c\n" +
	"\tclusterid\x18\x04 \x01(\tR\tclusterid\x12 \n" +
	"\vclustername\x18\x05 \x01(\tR\vclustername\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_uuid\x18\a \x01(\tR\apodUuid\x12\x19\n" +
	"\bpod_name\x18\b \x01(\tR\apodName\x127\n" +
	"\tpod_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bpodStart\x123\n" +
	"\apod_end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06podEnd\x12%\n" +
	"\x0econtainer_name\x18\v \x01(\tR\rcontainerName\x125\n" +
	"\blifetime\x18\f \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1f\n" +
	"\vcpu_seconds\x18\r \x01(\tR\n" +
	"cpuSeconds\x12%\n" +
	"\x0ememory_seconds\x18\x0e \x01(\tR\rmemorySeconds\x12\x1a\n" +
	"\bwarnings\x18\x0f \x03(\tR\bwarnings\x12'\n" +
	"\x0fcontainer_image\x18\x10 \x01(\tR\x0econtainerImage\x12 \n" +
	"\vannotations\x18\x11 \x03(\tR\vannotations\x12 \n" +
	"\vprojectname\x18\x12 \x01(\tR\vprojectname\x12\x1e\n" +
	"\n" +
	"tenantname\x18\x13 \x01(\tR\n" +
	"tenantname\x12&\n" +
	"\x0econtractnumber\x18\x14 \x01(\tR\x0econtractnumber\x12\x1a\n" +
	"\bdebtorid\x18\x15 \x01(\tR\bdebtorid\"\x9b\x01\n" +
	"\x1aContainerUsageAccumuluated\x125\n" +
	"\blifetime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1f\n" +
	"\vcpu_seconds\x18\x02 \x01(\tR\n" +
	"cpuSeconds\x12%\n" +
	"\x0ememory_seconds\x18\x03 \x01(\tR\rmemorySeconds2\xa2\x03\n" +
	"\n" +
	"PodService\x12[\n" +
	"\x05Added\x12*.metalstack.io.accounting.api.v1.PodReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12^\n" +
	"\bModified\x12*.metalstack.io.accounting.api.v1.PodReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12]\n" +
	"\aDeleted\x12*.metalstack.io.accounting.api.v1.PodReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12x\n" +
	"\x05Usage\x126.metalstack.io.accounting.api.v1.ContainerUsageRequest\x1a7.metalstack.io.accounting.api.v1.ContainerUsageResponseB\rZ\vpkg/apis/v1b\x06proto3"

var (
	file_metalstack_io_accounting_api_v1_pod_proto_rawDescOnce sync.Once
	file_metalstack_io_accounting_api_v1_pod_proto_rawDescData []byte
)

func file_metalstack_io_accounting_api_v1_pod_proto_rawDescGZIP() []byte {
	file_metalstack_io_accounting_api_v1_pod_proto_rawDescOnce.Do(func() {
		file_metalstack_io_accounting_api_v1_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_pod_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_pod_proto_rawDesc)))
	})
	return file_metalstack_io_accounting_api_v1_pod_proto_rawDescData
}

var file_metalstack_io_accounting_api_v1_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metalstack_io_accounting_api_v1_pod_proto_goTypes = []any{
	(*Container)(nil),                  // 0: metalstack.io.accounting.api.v1.Container
	(*PodReport)(nil),                  // 1: metalstack.io.accounting.api.v1.PodReport
	(*ContainerUsageRequest)(nil),      // 2: metalstack.io.accounting.api.v1.ContainerUsageRequest
	(*ContainerUsageResponse)(nil),     // 3: metalstack.io.accounting.api.v1.ContainerUsageResponse
	(*ContainerUsage)(nil),             // 4: metalstack.io.accounting.api.v1.ContainerUsage
	(*ContainerUsageAccumuluated)(nil), // 5: metalstack.io.accounting.api.v1.ContainerUsageAccumuluated
	(*KubernetesResourceReport)(nil),   // 6: metalstack.io.accounting.api.v1.KubernetesResourceReport
	(*UsageQuery)(nil),                 // 7: metalstack.io.accounting.api.v1.UsageQuery
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 9: google.protobuf.Duration
	(*Empty)(nil),                      // 10: metalstack.io.accounting.api.v1.Empty
}
var file_metalstack_io_accounting_api_v1_pod_proto_depIdxs = []int32{
	6,  // 0: metalstack.io.accounting.api.v1.PodReport.kubernetes_report:type_name -> metalstack.io.accounting.api.v1.KubernetesResourceReport
	0,  // 1: metalstack.io.accounting.api.v1.PodReport.containers:type_name -> metalstack.io.accounting.api.v1.Container
	7,  // 2: metalstack.io.accounting.api.v1.ContainerUsageRequest.query:type_name -> metalstack.io.accounting.api.v1.UsageQuery
	8,  // 3: metalstack.io.accounting.api.v1.ContainerUsageResponse.from:type_name -> google.protobuf.Timestamp
	8,  // 4: metalstack.io.accounting.api.v1.ContainerUsageResponse.to:type_name -> google.protobuf.Timestamp
	4,  // 5: metalstack.io.accounting.api.v1.ContainerUsageResponse.usage:type_name -> metalstack.io.accounting.api.v1.ContainerUsage
	5,  // 6: metalstack.io.accounting.api.v1.ContainerUsageResponse.accumulated_usage:type_name -> metalstack.io.accounting.api.v1.ContainerUsageAccumuluated
	8,  // 7: metalstack.io.accounting.api.v1.ContainerUsage.pod_start:type_name -> google.protobuf.Timestamp
	8,  // 8: metalstack.io.accounting.api.v1.ContainerUsage.pod_end:type_name -> google.protobuf.Timestamp
	9,  // 9: metalstack.io.accounting.api.v1.ContainerUsage.lifetime:type_name -> google.protobuf.Duration
	9,  // 10: metalstack.io.accounting.api.v1.ContainerUsageAccumuluated.lifetime:type_name -> google.protobuf.Duration
	1,  // 11: metalstack.io.accounting.api.v1.PodService.Added:input_type -> metalstack.io.accounting.api.v1.PodReport
	1,  // 12: metalstack.io.accounting.api.v1.PodService.Modified:input_type -> metalstack.io.accounting.api.v1.PodReport
	1,  // 13: metalstack.io.accounting.api.v1.PodService.Deleted:input_type -> metalstack.io.accounting.api.v1.PodReport
	2,  // 14: metalstack.io.accounting.api.v1.PodService.Usage:input_type -> metalstack.io.accounting.api.v1.ContainerUsageRequest
	10, // 15: metalstack.io.accounting.api.v1.PodService.Added:output_type -> metalstack.io.accounting.api.v1.Empty
	10, // 16: metalstack.io.accounting.api.v1.PodService.Modified:output_type -> metalstack.io.accounting.api.v1.Empty
	10, // 17: metalstack.io.accounting.api.v1.PodService.Deleted:output_type -> metalstack.io.accounting.api.v1.Empty
	3,  // 18: metalstack.io.accounting.api.v1.PodService.Usage:output_type -> metalstack.io.accounting.api.v1.ContainerUsageResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_metalstack_io_accounting_api_v1_pod_proto_init() }
func file_metalstack_io_accounting_api_v1_pod_proto_init() {
	if File_metalstack_io_accounting_api_v1_pod_proto != nil {
		return
	}
	file_metalstack_io_accounting_api_v1_common_proto_init()
	file_metalstack_io_accounting_api_v1_pod_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_pod_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metalstack_io_accounting_api_v1_pod_proto_goTypes,
		DependencyIndexes: file_metalstack_io_accounting_api_v1_pod_proto_depIdxs,
		MessageInfos:      file_metalstack_io_accounting_api_v1_pod_proto_msgTypes,
	}.Build()
	File_metalstack_io_accounting_api_v1_pod_proto = out.File
	file_metalstack_io_accounting_api_v1_pod_proto_goTypes = nil
	file_metalstack_io_accounting_api_v1_pod_proto_depIdxs = nil
}
