// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: metalstack/io/accounting/api/v1/s3.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	S3Service_BucketStats_FullMethodName = "/metalstack.io.accounting.api.v1.S3Service/BucketStats"
	S3Service_Usage_FullMethodName       = "/metalstack.io.accounting.api.v1.S3Service/Usage"
)

// S3ServiceClient is the client API for S3Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type S3ServiceClient interface {
	BucketStats(ctx context.Context, in *S3BucketReport, opts ...grpc.CallOption) (*Empty, error)
	Usage(ctx context.Context, in *S3UsageRequest, opts ...grpc.CallOption) (*S3UsageResponse, error)
}

type s3ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewS3ServiceClient(cc grpc.ClientConnInterface) S3ServiceClient {
	return &s3ServiceClient{cc}
}

func (c *s3ServiceClient) BucketStats(ctx context.Context, in *S3BucketReport, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, S3Service_BucketStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3ServiceClient) Usage(ctx context.Context, in *S3UsageRequest, opts ...grpc.CallOption) (*S3UsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(S3UsageResponse)
	err := c.cc.Invoke(ctx, S3Service_Usage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S3ServiceServer is the server API for S3Service service.
// All implementations should embed UnimplementedS3ServiceServer
// for forward compatibility.
type S3ServiceServer interface {
	BucketStats(context.Context, *S3BucketReport) (*Empty, error)
	Usage(context.Context, *S3UsageRequest) (*S3UsageResponse, error)
}

// UnimplementedS3ServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedS3ServiceServer struct{}

func (UnimplementedS3ServiceServer) BucketStats(context.Context, *S3BucketReport) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BucketStats not implemented")
}
func (UnimplementedS3ServiceServer) Usage(context.Context, *S3UsageRequest) (*S3UsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Usage not implemented")
}
func (UnimplementedS3ServiceServer) testEmbeddedByValue() {}

// UnsafeS3ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S3ServiceServer will
// result in compilation errors.
type UnsafeS3ServiceServer interface {
	mustEmbedUnimplementedS3ServiceServer()
}

func RegisterS3ServiceServer(s grpc.ServiceRegistrar, srv S3ServiceServer) {
	// If the following call panics, it indicates UnimplementedS3ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&S3Service_ServiceDesc, srv)
}

func _S3Service_BucketStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S3BucketReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3ServiceServer).BucketStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3Service_BucketStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3ServiceServer).BucketStats(ctx, req.(*S3BucketReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3Service_Usage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S3UsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3ServiceServer).Usage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3Service_Usage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3ServiceServer).Usage(ctx, req.(*S3UsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// S3Service_ServiceDesc is the grpc.ServiceDesc for S3Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S3Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metalstack.io.accounting.api.v1.S3Service",
	HandlerType: (*S3ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BucketStats",
			Handler:    _S3Service_BucketStats_Handler,
		},
		{
			MethodName: "Usage",
			Handler:    _S3Service_Usage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metalstack/io/accounting/api/v1/s3.proto",
}
