// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: metalstack/io/accounting/api/v1/vm.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cpus          string                 `protobuf:"bytes,3,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory        string                 `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VM) Reset() {
	*x = VM{}
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VM) ProtoMessage() {}

func (x *VM) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VM.ProtoReflect.Descriptor instead.
func (*VM) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_vm_proto_rawDescGZIP(), []int{0}
}

func (x *VM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VM) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VM) GetCpus() string {
	if x != nil {
		return x.Cpus
	}
	return ""
}

func (x *VM) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *VM) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type VMReport struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	KubernetesReport *KubernetesResourceReport `protobuf:"bytes,1,opt,name=kubernetes_report,json=kubernetesReport,proto3" json:"kubernetes_report,omitempty"` // Kubernetes Bezeichnung irreführend und nicht sicher ob nötig; Kann in Report und start_date, end_date unterteilt werden da namespace nicht nötig?
	Vm               *VM                       `protobuf:"bytes,2,opt,name=vm,proto3" json:"vm,omitempty"`
	Annotations      []string                  `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VMReport) Reset() {
	*x = VMReport{}
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMReport) ProtoMessage() {}

func (x *VMReport) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMReport.ProtoReflect.Descriptor instead.
func (*VMReport) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_vm_proto_rawDescGZIP(), []int{1}
}

func (x *VMReport) GetKubernetesReport() *KubernetesResourceReport {
	if x != nil {
		return x.KubernetesReport
	}
	return nil
}

func (x *VMReport) GetVm() *VM {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *VMReport) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type VMUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *UsageQuery            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Annotations   []string               `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMUsageRequest) Reset() {
	*x = VMUsageRequest{}
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMUsageRequest) ProtoMessage() {}

func (x *VMUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMUsageRequest.ProtoReflect.Descriptor instead.
func (*VMUsageRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_vm_proto_rawDescGZIP(), []int{2}
}

func (x *VMUsageRequest) GetQuery() *UsageQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *VMUsageRequest) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type VMUsageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	From             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Usage            *VMUsage               `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	AccumulatedUsage *VMUsageAccumuluated   `protobuf:"bytes,4,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VMUsageResponse) Reset() {
	*x = VMUsageResponse{}
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMUsageResponse) ProtoMessage() {}

func (x *VMUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMUsageResponse.ProtoReflect.Descriptor instead.
func (*VMUsageResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_vm_proto_rawDescGZIP(), []int{3}
}

func (x *VMUsageResponse) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *VMUsageResponse) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *VMUsageResponse) GetUsage() *VMUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *VMUsageResponse) GetAccumulatedUsage() *VMUsageAccumuluated {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

type VMUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VmStart        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=vm_start,json=vmStart,proto3" json:"vm_start,omitempty"`
	VmEnd          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=vm_end,json=vmEnd,proto3" json:"vm_end,omitempty"`
	Lifetime       *durationpb.Duration   `protobuf:"bytes,5,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	CpuSeconds     string                 `protobuf:"bytes,6,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	MemorySeconds  string                 `protobuf:"bytes,7,opt,name=memory_seconds,json=memorySeconds,proto3" json:"memory_seconds,omitempty"`
	Warnings       []string               `protobuf:"bytes,8,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Annotations    []string               `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty"`
	TenantId       string                 `protobuf:"bytes,10,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantName     string                 `protobuf:"bytes,11,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	ProjectId      string                 `protobuf:"bytes,12,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName    string                 `protobuf:"bytes,13,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ClusterId      string                 `protobuf:"bytes,14,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClusterName    string                 `protobuf:"bytes,15,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Contractnumber string                 `protobuf:"bytes,16,opt,name=contractnumber,proto3" json:"contractnumber,omitempty"`
	Debtorid       string                 `protobuf:"bytes,17,opt,name=debtorid,proto3" json:"debtorid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VMUsage) Reset() {
	*x = VMUsage{}
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMUsage) ProtoMessage() {}

func (x *VMUsage) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMUsage.ProtoReflect.Descriptor instead.
func (*VMUsage) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_vm_proto_rawDescGZIP(), []int{4}
}

func (x *VMUsage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VMUsage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMUsage) GetVmStart() *timestamppb.Timestamp {
	if x != nil {
		return x.VmStart
	}
	return nil
}

func (x *VMUsage) GetVmEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.VmEnd
	}
	return nil
}

func (x *VMUsage) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *VMUsage) GetCpuSeconds() string {
	if x != nil {
		return x.CpuSeconds
	}
	return ""
}

func (x *VMUsage) GetMemorySeconds() string {
	if x != nil {
		return x.MemorySeconds
	}
	return ""
}

func (x *VMUsage) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *VMUsage) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *VMUsage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VMUsage) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *VMUsage) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *VMUsage) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *VMUsage) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *VMUsage) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *VMUsage) GetContractnumber() string {
	if x != nil {
		return x.Contractnumber
	}
	return ""
}

func (x *VMUsage) GetDebtorid() string {
	if x != nil {
		return x.Debtorid
	}
	return ""
}

type VMUsageAccumuluated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	CpuSeconds    string                 `protobuf:"bytes,2,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	MemorySeconds string                 `protobuf:"bytes,3,opt,name=memory_seconds,json=memorySeconds,proto3" json:"memory_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMUsageAccumuluated) Reset() {
	*x = VMUsageAccumuluated{}
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMUsageAccumuluated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMUsageAccumuluated) ProtoMessage() {}

func (x *VMUsageAccumuluated) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_accounting_api_v1_vm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMUsageAccumuluated.ProtoReflect.Descriptor instead.
func (*VMUsageAccumuluated) Descriptor() ([]byte, []int) {
	return file_metalstack_io_accounting_api_v1_vm_proto_rawDescGZIP(), []int{5}
}

func (x *VMUsageAccumuluated) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *VMUsageAccumuluated) GetCpuSeconds() string {
	if x != nil {
		return x.CpuSeconds
	}
	return ""
}

func (x *VMUsageAccumuluated) GetMemorySeconds() string {
	if x != nil {
		return x.MemorySeconds
	}
	return ""
}

var File_metalstack_io_accounting_api_v1_vm_proto protoreflect.FileDescriptor

const file_metalstack_io_accounting_api_v1_vm_proto_rawDesc = "" +
	"\n" +
	"(metalstack/io/accounting/api/v1/vm.proto\x12\x1fmetalstack.io.accounting.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,metalstack/io/accounting/api/v1/common.proto\"n\n" +
	"\x02VM\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04cpus\x18\x03 \x01(\tR\x04cpus\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\tR\x06memory\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"\xc9\x01\n" +
	"\bVMReport\x12f\n" +
	"\x11kubernetes_report\x18\x01 \x01(\v29.metalstack.io.accounting.api.v1.KubernetesResourceReportR\x10kubernetesReport\x123\n" +
	"\x02vm\x18\x02 \x01(\v2#.metalstack.io.accounting.api.v1.VMR\x02vm\x12 \n" +
	"\vannotations\x18\x03 \x03(\tR\vannotations\"u\n" +
	"\x0eVMUsageRequest\x12A\n" +
	"\x05query\x18\x01 \x01(\v2+.metalstack.io.accounting.api.v1.UsageQueryR\x05query\x12 \n" +
	"\vannotations\x18\x03 \x03(\tR\vannotations\"\x90\x02\n" +
	"\x0fVMUsageResponse\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12>\n" +
	"\x05usage\x18\x03 \x01(\v2(.metalstack.io.accounting.api.v1.VMUsageR\x05usage\x12a\n" +
	"\x11accumulated_usage\x18\x04 \x01(\v24.metalstack.io.accounting.api.v1.VMUsageAccumuluatedR\x10accumulatedUsage\"\xde\x04\n" +
	"\aVMUsage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bvm_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\avmStart\x121\n" +
	"\x06vm_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05vmEnd\x125\n" +
	"\blifetime\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1f\n" +
	"\vcpu_seconds\x18\x06 \x01(\tR\n" +
	"cpuSeconds\x12%\n" +
	"\x0ememory_seconds\x18\a \x01(\tR\rmemorySeconds\x12\x1a\n" +
	"\bwarnings\x18\b \x03(\tR\bwarnings\x12 \n" +
	"\vannotations\x18\t \x03(\tR\vannotations\x12\x1b\n" +
	"\ttenant_id\x18\n" +
	" \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\v \x01(\tR\n" +
	"tenantName\x12\x1d\n" +
	"\n" +
	"project_id\x18\f \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\r \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x0e \x01(\tR\tclusterId\x12!\n" +
	"\fcluster_name\x18\x0f \x01(\tR\vclusterName\x12&\n" +
	"\x0econtractnumber\x18\x10 \x01(\tR\x0econtractnumber\x12\x1a\n" +
	"\bdebtorid\x18\x11 \x01(\tR\bdebtorid\"\x94\x01\n" +
	"\x13VMUsageAccumuluated\x125\n" +
	"\blifetime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x1f\n" +
	"\vcpu_seconds\x18\x02 \x01(\tR\n" +
	"cpuSeconds\x12%\n" +
	"\x0ememory_seconds\x18\x03 \x01(\tR\rmemorySeconds2\x90\x03\n" +
	"\tVMService\x12Z\n" +
	"\x05Added\x12).metalstack.io.accounting.api.v1.VMReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12]\n" +
	"\bModified\x12).metalstack.io.accounting.api.v1.VMReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12\\\n" +
	"\aDeleted\x12).metalstack.io.accounting.api.v1.VMReport\x1a&.metalstack.io.accounting.api.v1.Empty\x12j\n" +
	"\x05Usage\x12/.metalstack.io.accounting.api.v1.VMUsageRequest\x1a0.metalstack.io.accounting.api.v1.VMUsageResponseB\rZ\vpkg/apis/v1b\x06proto3"

var (
	file_metalstack_io_accounting_api_v1_vm_proto_rawDescOnce sync.Once
	file_metalstack_io_accounting_api_v1_vm_proto_rawDescData []byte
)

func file_metalstack_io_accounting_api_v1_vm_proto_rawDescGZIP() []byte {
	file_metalstack_io_accounting_api_v1_vm_proto_rawDescOnce.Do(func() {
		file_metalstack_io_accounting_api_v1_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_vm_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_vm_proto_rawDesc)))
	})
	return file_metalstack_io_accounting_api_v1_vm_proto_rawDescData
}

var file_metalstack_io_accounting_api_v1_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metalstack_io_accounting_api_v1_vm_proto_goTypes = []any{
	(*VM)(nil),                       // 0: metalstack.io.accounting.api.v1.VM
	(*VMReport)(nil),                 // 1: metalstack.io.accounting.api.v1.VMReport
	(*VMUsageRequest)(nil),           // 2: metalstack.io.accounting.api.v1.VMUsageRequest
	(*VMUsageResponse)(nil),          // 3: metalstack.io.accounting.api.v1.VMUsageResponse
	(*VMUsage)(nil),                  // 4: metalstack.io.accounting.api.v1.VMUsage
	(*VMUsageAccumuluated)(nil),      // 5: metalstack.io.accounting.api.v1.VMUsageAccumuluated
	(*KubernetesResourceReport)(nil), // 6: metalstack.io.accounting.api.v1.KubernetesResourceReport
	(*UsageQuery)(nil),               // 7: metalstack.io.accounting.api.v1.UsageQuery
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 9: google.protobuf.Duration
	(*Empty)(nil),                    // 10: metalstack.io.accounting.api.v1.Empty
}
var file_metalstack_io_accounting_api_v1_vm_proto_depIdxs = []int32{
	6,  // 0: metalstack.io.accounting.api.v1.VMReport.kubernetes_report:type_name -> metalstack.io.accounting.api.v1.KubernetesResourceReport
	0,  // 1: metalstack.io.accounting.api.v1.VMReport.vm:type_name -> metalstack.io.accounting.api.v1.VM
	7,  // 2: metalstack.io.accounting.api.v1.VMUsageRequest.query:type_name -> metalstack.io.accounting.api.v1.UsageQuery
	8,  // 3: metalstack.io.accounting.api.v1.VMUsageResponse.from:type_name -> google.protobuf.Timestamp
	8,  // 4: metalstack.io.accounting.api.v1.VMUsageResponse.to:type_name -> google.protobuf.Timestamp
	4,  // 5: metalstack.io.accounting.api.v1.VMUsageResponse.usage:type_name -> metalstack.io.accounting.api.v1.VMUsage
	5,  // 6: metalstack.io.accounting.api.v1.VMUsageResponse.accumulated_usage:type_name -> metalstack.io.accounting.api.v1.VMUsageAccumuluated
	8,  // 7: metalstack.io.accounting.api.v1.VMUsage.vm_start:type_name -> google.protobuf.Timestamp
	8,  // 8: metalstack.io.accounting.api.v1.VMUsage.vm_end:type_name -> google.protobuf.Timestamp
	9,  // 9: metalstack.io.accounting.api.v1.VMUsage.lifetime:type_name -> google.protobuf.Duration
	9,  // 10: metalstack.io.accounting.api.v1.VMUsageAccumuluated.lifetime:type_name -> google.protobuf.Duration
	1,  // 11: metalstack.io.accounting.api.v1.VMService.Added:input_type -> metalstack.io.accounting.api.v1.VMReport
	1,  // 12: metalstack.io.accounting.api.v1.VMService.Modified:input_type -> metalstack.io.accounting.api.v1.VMReport
	1,  // 13: metalstack.io.accounting.api.v1.VMService.Deleted:input_type -> metalstack.io.accounting.api.v1.VMReport
	2,  // 14: metalstack.io.accounting.api.v1.VMService.Usage:input_type -> metalstack.io.accounting.api.v1.VMUsageRequest
	10, // 15: metalstack.io.accounting.api.v1.VMService.Added:output_type -> metalstack.io.accounting.api.v1.Empty
	10, // 16: metalstack.io.accounting.api.v1.VMService.Modified:output_type -> metalstack.io.accounting.api.v1.Empty
	10, // 17: metalstack.io.accounting.api.v1.VMService.Deleted:output_type -> metalstack.io.accounting.api.v1.Empty
	3,  // 18: metalstack.io.accounting.api.v1.VMService.Usage:output_type -> metalstack.io.accounting.api.v1.VMUsageResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_metalstack_io_accounting_api_v1_vm_proto_init() }
func file_metalstack_io_accounting_api_v1_vm_proto_init() {
	if File_metalstack_io_accounting_api_v1_vm_proto != nil {
		return
	}
	file_metalstack_io_accounting_api_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_io_accounting_api_v1_vm_proto_rawDesc), len(file_metalstack_io_accounting_api_v1_vm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metalstack_io_accounting_api_v1_vm_proto_goTypes,
		DependencyIndexes: file_metalstack_io_accounting_api_v1_vm_proto_depIdxs,
		MessageInfos:      file_metalstack_io_accounting_api_v1_vm_proto_msgTypes,
	}.Build()
	File_metalstack_io_accounting_api_v1_vm_proto = out.File
	file_metalstack_io_accounting_api_v1_vm_proto_goTypes = nil
	file_metalstack_io_accounting_api_v1_vm_proto_depIdxs = nil
}
