syntax = "proto3";

package metalstack.io.accounting.api.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "metalstack/io/accounting/api/v1/common.proto";

option go_package = "pkg/apis/v1";

service VMService {
  rpc Added(VMReport) returns (Empty);
  rpc Modified(VMReport) returns (Empty);
  rpc Deleted(VMReport) returns (Empty);

  rpc Usage(VMUsageRequest) returns (VMUsageResponse);
}

message VM {
  string uuid = 1;
  string hostname = 2;
  string fqdname = 3;
  string cpus = 4;
  string memory = 5;
  string image = 6;
}

message VMReport {
  string tenant = 1;
  string projectid = 2;
  string requestid = 3;
  google.protobuf.Timestamp timestamp = 4;
  google.protobuf.Timestamp start_date = 5;
  google.protobuf.Timestamp end_date = 6;
  VM vm = 7;
  repeated string annotations = 8;
}

message VMUsageRequest {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2;
  optional string tenant = 3;
  optional string projectid = 4;
  repeated string annotations = 5;
}

message VMUsageResponse {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2;
  VMUsage usage = 3;
  VMUsageAccumuluated accumulated_usage = 4;
}

message VMUsage {
  string uuid = 1;
  string hostname = 2;
  string fqdname = 3;
  google.protobuf.Timestamp vm_start = 4;
  google.protobuf.Timestamp vm_end = 5;
  google.protobuf.Duration lifetime = 6;
  string cpu_seconds = 7;
  string memory_seconds = 8;
  repeated string warnings = 9;
  repeated string annotations = 10;
  string tenant = 11;
  string project_id = 12;
  string request_id = 13;
}

message VMUsageAccumuluated {
  google.protobuf.Duration lifetime = 1;
  string cpu_seconds = 2;
  string memory_seconds = 3;
}
