syntax = "proto3";

package metalstack.io.accounting.api.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "metalstack/io/accounting/api/v1/common.proto";

option go_package = "pkg/apis/v1";

service VMVolumeService {
  rpc Added(VMVolumeReport) returns (Empty);
  rpc Modified(VMVolumeReport) returns (Empty);
  rpc Deleted(VMVolumeReport) returns (Empty);

  rpc Usage(VMVolumeUsageRequest) returns (VMVolumeUsageResponse);
}

message VMVolume {
  string name = 1;
  string uuid = 2;
  string storage_type = 3;
  string size = 4;
}

message VMVolumeReport {
  KubernetesResourceReport kubernetes_report = 1;
  VMVolume vm_volume = 2;
  repeated string annotations = 3;
}

message VMVolumeUsageRequest {
  UsageQuery query = 1;
  optional string storage_type = 2;
  repeated string annotations = 3;
}

message VMVolumeUsageResponse {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2;
  VMVolumeUsage usage = 3;
  VMVolumeUsageAccumuluated accumulated_usage = 4;
}

message VMVolumeUsage {
  string name = 1;
  string uuid = 2;
  google.protobuf.Timestamp start = 3;
  google.protobuf.Timestamp end = 4;
  google.protobuf.Duration lifetime = 5;
  string capacity_seconds = 6;
  repeated string warnings = 7;
  repeated string annotations = 8;
  string tenant_id = 9;
  string tenant_name = 10;
  string project_id = 11;
  string project_name = 12;
  string cluster_id = 13;
  string cluster_name = 14;
  string contractnumber = 15;
  string debtorid = 16;
}

message VMVolumeUsageAccumuluated {
  google.protobuf.Duration lifetime = 1;
  string capacity_seconds = 2;
}
