package main

import (
	"bufio"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	t "text/template"
)

const (
	templatePath = "buf.gen.yaml.tmpl"
	outputPath   = "buf.gen.yaml"
)

type data struct {
	Header       []string
	ImportPaths  []string
	ModulePrefix string
}

func newData(importPaths []string) data {
	return data{
		Header: []string{
			"# Code generated by buf.gen.yaml.tmp. DO NOT EDIT.",
			"# Edit the template instead.",
		},
		ModulePrefix: "github.com/fi-ts/accounting-go",
		ImportPaths:  importPaths,
	}
}

func main() {
	fmt.Printf("generating %s from %s\n", outputPath, templatePath)
	template, err := t.ParseFiles(templatePath)
	if err != nil {
		panic(err)
	}

	var importPaths []string

	fmt.Println("collecting import paths")
	err = filepath.Walk(".", func(path string, info fs.FileInfo, err error) error {
		if info.IsDir() {
			return nil
		}

		if strings.HasSuffix(info.Name(), ".proto") {
			importPath := fmt.Sprintf(
				"- M%s=github.com/fi-ts/accounting-go/%s",
				path,
				extractGoPackage(path))
			importPaths = append(importPaths, importPath)
		}
		return nil
	})

	if err != nil {
		panic(err)
	}

	output, err := os.Create(outputPath)
	if err != nil {
		panic(err)
	}

	if err = template.Execute(output, newData(importPaths)); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s\n", outputPath)
}

func extractGoPackage(path string) string {
	var goPackage string

	file, err := os.Open(path)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		if strings.HasPrefix(line, "option go_package") {
			_, goPackage, _ = strings.Cut(line, "\"")
			goPackage, _, _ = strings.Cut(goPackage, "\"")
			break
		}
	}

	if err := scanner.Err(); err != nil {
		panic(err)
	}
	return goPackage
}
