// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fi-ts/accounting-go/pkg/apis/mvm/v1"
	v10 "github.com/fi-ts/accounting-go/pkg/apis/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewManagedVMServiceClient creates a new instance of ManagedVMServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagedVMServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagedVMServiceClient {
	mock := &ManagedVMServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ManagedVMServiceClient is an autogenerated mock type for the ManagedVMServiceClient type
type ManagedVMServiceClient struct {
	mock.Mock
}

type ManagedVMServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ManagedVMServiceClient) EXPECT() *ManagedVMServiceClient_Expecter {
	return &ManagedVMServiceClient_Expecter{mock: &_m.Mock}
}

// Added provides a mock function for the type ManagedVMServiceClient
func (_mock *ManagedVMServiceClient) Added(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption) (*v10.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Added")
	}

	var r0 *v10.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) (*v10.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) *v10.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceClient_Added_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Added'
type ManagedVMServiceClient_Added_Call struct {
	*mock.Call
}

// Added is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ManagedVMReport
//   - opts ...grpc.CallOption
func (_e *ManagedVMServiceClient_Expecter) Added(ctx any, in any, opts ...any) *ManagedVMServiceClient_Added_Call {
	return &ManagedVMServiceClient_Added_Call{Call: _e.mock.On("Added",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *ManagedVMServiceClient_Added_Call) Run(run func(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption)) *ManagedVMServiceClient_Added_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ManagedVMServiceClient_Added_Call) Return(empty *v10.Empty, err error) *ManagedVMServiceClient_Added_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ManagedVMServiceClient_Added_Call) RunAndReturn(run func(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption) (*v10.Empty, error)) *ManagedVMServiceClient_Added_Call {
	_c.Call.Return(run)
	return _c
}

// Deleted provides a mock function for the type ManagedVMServiceClient
func (_mock *ManagedVMServiceClient) Deleted(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption) (*v10.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deleted")
	}

	var r0 *v10.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) (*v10.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) *v10.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceClient_Deleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deleted'
type ManagedVMServiceClient_Deleted_Call struct {
	*mock.Call
}

// Deleted is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ManagedVMReport
//   - opts ...grpc.CallOption
func (_e *ManagedVMServiceClient_Expecter) Deleted(ctx any, in any, opts ...any) *ManagedVMServiceClient_Deleted_Call {
	return &ManagedVMServiceClient_Deleted_Call{Call: _e.mock.On("Deleted",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *ManagedVMServiceClient_Deleted_Call) Run(run func(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption)) *ManagedVMServiceClient_Deleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ManagedVMServiceClient_Deleted_Call) Return(empty *v10.Empty, err error) *ManagedVMServiceClient_Deleted_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ManagedVMServiceClient_Deleted_Call) RunAndReturn(run func(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption) (*v10.Empty, error)) *ManagedVMServiceClient_Deleted_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function for the type ManagedVMServiceClient
func (_mock *ManagedVMServiceClient) Modified(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption) (*v10.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 *v10.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) (*v10.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) *v10.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMReport, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceClient_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type ManagedVMServiceClient_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ManagedVMReport
//   - opts ...grpc.CallOption
func (_e *ManagedVMServiceClient_Expecter) Modified(ctx any, in any, opts ...any) *ManagedVMServiceClient_Modified_Call {
	return &ManagedVMServiceClient_Modified_Call{Call: _e.mock.On("Modified",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *ManagedVMServiceClient_Modified_Call) Run(run func(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption)) *ManagedVMServiceClient_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMReport
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMReport)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ManagedVMServiceClient_Modified_Call) Return(empty *v10.Empty, err error) *ManagedVMServiceClient_Modified_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *ManagedVMServiceClient_Modified_Call) RunAndReturn(run func(ctx context.Context, in *v1.ManagedVMReport, opts ...grpc.CallOption) (*v10.Empty, error)) *ManagedVMServiceClient_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type ManagedVMServiceClient
func (_mock *ManagedVMServiceClient) Usage(ctx context.Context, in *v1.ManagedVMUsageRequest, opts ...grpc.CallOption) (*v1.ManagedVMUsageResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *v1.ManagedVMUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMUsageRequest, ...grpc.CallOption) (*v1.ManagedVMUsageResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ManagedVMUsageRequest, ...grpc.CallOption) *v1.ManagedVMUsageResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ManagedVMUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ManagedVMUsageRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ManagedVMServiceClient_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type ManagedVMServiceClient_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ManagedVMUsageRequest
//   - opts ...grpc.CallOption
func (_e *ManagedVMServiceClient_Expecter) Usage(ctx any, in any, opts ...any) *ManagedVMServiceClient_Usage_Call {
	return &ManagedVMServiceClient_Usage_Call{Call: _e.mock.On("Usage",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *ManagedVMServiceClient_Usage_Call) Run(run func(ctx context.Context, in *v1.ManagedVMUsageRequest, opts ...grpc.CallOption)) *ManagedVMServiceClient_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ManagedVMUsageRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ManagedVMUsageRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ManagedVMServiceClient_Usage_Call) Return(managedVMUsageResponse *v1.ManagedVMUsageResponse, err error) *ManagedVMServiceClient_Usage_Call {
	_c.Call.Return(managedVMUsageResponse, err)
	return _c
}

func (_c *ManagedVMServiceClient_Usage_Call) RunAndReturn(run func(ctx context.Context, in *v1.ManagedVMUsageRequest, opts ...grpc.CallOption) (*v1.ManagedVMUsageResponse, error)) *ManagedVMServiceClient_Usage_Call {
	_c.Call.Return(run)
	return _c
}
